"""
Test torchspin Hamiltonian functions against MATLAB EasySpin reference data.

These tests load .mat files generated by tests/data/generate_ref_hamiltonians.m
and compare torchspin outputs to the MATLAB reference implementation.
"""

import pytest
import torch
import numpy as np
from pathlib import Path
from scipy.io import loadmat

from torchspin import ham
from torchspin.spinsystem import SpinSystem


# Path to reference data directory
DATA_DIR = Path(__file__).parent.parent.parent / "tests" / "data"


def mat_to_torch(mat_array):
    """Convert MATLAB complex array to torch tensor."""
    if np.iscomplexobj(mat_array):
        return torch.tensor(mat_array, dtype=torch.complex128)
    else:
        return torch.tensor(mat_array, dtype=torch.float64)


def assert_matrices_close(torch_mat, matlab_mat, rtol=1e-12, atol=1e-14, name="matrix"):
    """Assert two matrices are close within numerical tolerance."""
    torch_mat_np = torch_mat.cpu().numpy()
    matlab_mat_np = np.asarray(matlab_mat)
    
    # Check shape
    assert torch_mat_np.shape == matlab_mat_np.shape, \
        f"{name} shape mismatch: torch {torch_mat_np.shape} vs MATLAB {matlab_mat_np.shape}"
    
    # Check values
    if np.iscomplexobj(matlab_mat_np):
        # Complex comparison
        diff = np.abs(torch_mat_np - matlab_mat_np)
        max_diff = np.max(diff)
        rel_diff = diff / (np.abs(matlab_mat_np) + atol)
        max_rel_diff = np.max(rel_diff)
        
        assert max_diff < atol or max_rel_diff < rtol, \
            f"{name} mismatch: max_diff={max_diff:.2e}, max_rel_diff={max_rel_diff:.2e}"
    else:
        # Real comparison
        assert np.allclose(torch_mat_np, matlab_mat_np, rtol=rtol, atol=atol), \
            f"{name} mismatch: max diff = {np.max(np.abs(torch_mat_np - matlab_mat_np)):.2e}"


def test_ham_zeeman_isotropic():
    """Test 1: Zeeman with isotropic g, S=1/2."""
    # Load MATLAB reference
    mat_data = loadmat(DATA_DIR / "ref_ham_ez_iso.mat")
    H0_ref = mat_to_torch(mat_data["H1_0"])
    mux_ref = mat_to_torch(mat_data["mux1"])
    muy_ref = mat_to_torch(mat_data["muy1"])
    muz_ref = mat_to_torch(mat_data["muz1"])
    
    # Create torchspin system
    sys = SpinSystem(S=1/2, g=2.0)
    
    # Compute with torchspin
    H0, mux, muy, muz = ham(sys)
    
    # Compare
    assert_matrices_close(H0, H0_ref, name="H0 (Zeeman iso)")
    assert_matrices_close(mux, mux_ref, name="mux (Zeeman iso)")
    assert_matrices_close(muy, muy_ref, name="muy (Zeeman iso)")
    assert_matrices_close(muz, muz_ref, name="muz (Zeeman iso)")


def test_ham_zeeman_anisotropic():
    """Test 2: Zeeman with anisotropic g, S=1/2."""
    mat_data = loadmat(DATA_DIR / "ref_ham_ez_aniso.mat")
    H0_ref = mat_to_torch(mat_data["H2_0"])
    mux_ref = mat_to_torch(mat_data["mux2"])
    muy_ref = mat_to_torch(mat_data["muy2"])
    muz_ref = mat_to_torch(mat_data["muz2"])
    
    sys = SpinSystem(
        S=1/2,
        g=[2.0, 2.1, 2.2],
        gFrame=[0, 0, 0]
    )
    
    H0, mux, muy, muz = ham(sys)
    
    assert_matrices_close(H0, H0_ref, name="H0 (Zeeman aniso)")
    assert_matrices_close(mux, mux_ref, name="mux (Zeeman aniso)")
    assert_matrices_close(muy, muy_ref, name="muy (Zeeman aniso)")
    assert_matrices_close(muz, muz_ref, name="muz (Zeeman aniso)")


def test_ham_zfs_axial():
    """Test 3: Zero-field splitting, axial D, S=1."""
    mat_data = loadmat(DATA_DIR / "ref_ham_zf_axial.mat")
    H0_ref = mat_to_torch(mat_data["H3_0"])
    mux_ref = mat_to_torch(mat_data["mux3"])
    muy_ref = mat_to_torch(mat_data["muy3"])
    muz_ref = mat_to_torch(mat_data["muz3"])
    
    sys = SpinSystem(
        S=1,
        g=[2.0, 2.0, 2.0],
        D=[-100, -100, 200],  # Dxx, Dyy, Dzz in MHz
        DFrame=[0, 0, 0]
    )
    
    H0, mux, muy, muz = ham(sys)
    
    assert_matrices_close(H0, H0_ref, name="H0 (ZFS axial)")
    assert_matrices_close(mux, mux_ref, name="mux (ZFS axial)")
    assert_matrices_close(muy, muy_ref, name="muy (ZFS axial)")
    assert_matrices_close(muz, muz_ref, name="muz (ZFS axial)")


def test_ham_zfs_rhombic():
    """Test 4: Zero-field splitting, rhombic D, S=1."""
    mat_data = loadmat(DATA_DIR / "ref_ham_zf_rhombic.mat")
    H0_ref = mat_to_torch(mat_data["H4_0"])
    mux_ref = mat_to_torch(mat_data["mux4"])
    muy_ref = mat_to_torch(mat_data["muy4"])
    muz_ref = mat_to_torch(mat_data["muz4"])
    
    sys = SpinSystem(
        S=1,
        g=[2.0, 2.0, 2.0],
        D=[-150, -50, 200],
        DFrame=[0, 0, 0]
    )
    
    H0, mux, muy, muz = ham(sys)
    
    assert_matrices_close(H0, H0_ref, name="H0 (ZFS rhombic)")
    assert_matrices_close(mux, mux_ref, name="mux (ZFS rhombic)")
    assert_matrices_close(muy, muy_ref, name="muy (ZFS rhombic)")
    assert_matrices_close(muz, muz_ref, name="muz (ZFS rhombic)")


def test_ham_hyperfine_14N():
    """Test 5: Hyperfine, S=1/2 with single 14N nucleus."""
    mat_data = loadmat(DATA_DIR / "ref_ham_hf_14N.mat")
    H0_ref = mat_to_torch(mat_data["H5_0"])
    mux_ref = mat_to_torch(mat_data["mux5"])
    muy_ref = mat_to_torch(mat_data["muy5"])
    muz_ref = mat_to_torch(mat_data["muz5"])
    
    sys = SpinSystem(
        S=1/2,
        g=[2.006, 2.006, 2.002],
        Nucs="14N",
        A=[20, 20, 90],  # MHz
        AFrame=[0, 0, 0]
    )
    
    H0, mux, muy, muz = ham(sys)
    
    assert_matrices_close(H0, H0_ref, name="H0 (Hyperfine 14N)")
    assert_matrices_close(mux, mux_ref, name="mux (Hyperfine 14N)")
    assert_matrices_close(muy, muy_ref, name="muy (Hyperfine 14N)")
    assert_matrices_close(muz, muz_ref, name="muz (Hyperfine 14N)")


def test_ham_hyperfine_multi():
    """Test 6: Hyperfine, S=1/2 with two nuclei (14N + 1H)."""
    mat_data = loadmat(DATA_DIR / "ref_ham_hf_multiNuc.mat")
    H0_ref = mat_to_torch(mat_data["H6_0"])
    mux_ref = mat_to_torch(mat_data["mux6"])
    muy_ref = mat_to_torch(mat_data["muy6"])
    muz_ref = mat_to_torch(mat_data["muz6"])
    
    sys = SpinSystem(
        S=1/2,
        g=[2.006, 2.006, 2.002],
        Nucs="14N,1H",
        A=[[20, 20, 90], [5, 5, 15]],  # MHz
        AFrame=[[0, 0, 0], [0, 0, 0]]
    )
    
    H0, mux, muy, muz = ham(sys)
    
    assert_matrices_close(H0, H0_ref, name="H0 (Hyperfine multi)")
    assert_matrices_close(mux, mux_ref, name="mux (Hyperfine multi)")
    assert_matrices_close(muy, muy_ref, name="muy (Hyperfine multi)")
    assert_matrices_close(muz, muz_ref, name="muz (Hyperfine multi)")


def test_ham_electron_electron():
    """Test 7: Electron-electron coupling, two S=1/2."""
    mat_data = loadmat(DATA_DIR / "ref_ham_ee_twospin.mat")
    H0_ref = mat_to_torch(mat_data["H7_0"])
    mux_ref = mat_to_torch(mat_data["mux7"])
    muy_ref = mat_to_torch(mat_data["muy7"])
    muz_ref = mat_to_torch(mat_data["muz7"])
    
    sys = SpinSystem(
        S=[1/2, 1/2],
        g=[[2.0, 2.0, 2.0], [2.0, 2.0, 2.0]],
        ee=[10, 10, 20],  # MHz
        eeFrame=[0, 0, 0]
    )
    
    H0, mux, muy, muz = ham(sys)
    
    assert_matrices_close(H0, H0_ref, name="H0 (ee coupling)")
    assert_matrices_close(mux, mux_ref, name="mux (ee coupling)")
    assert_matrices_close(muy, muy_ref, name="muy (ee coupling)")
    assert_matrices_close(muz, muz_ref, name="muz (ee coupling)")


def test_ham_combined():
    """Test 8: Combined g + A terms, S=1/2 with 14N."""
    mat_data = loadmat(DATA_DIR / "ref_ham_combined.mat")
    H0_ref = mat_to_torch(mat_data["H8_0"])
    mux_ref = mat_to_torch(mat_data["mux8"])
    muy_ref = mat_to_torch(mat_data["muy8"])
    muz_ref = mat_to_torch(mat_data["muz8"])
    
    sys = SpinSystem(
        S=1/2,
        g=[2.009, 2.006, 2.002],
        gFrame=[0, 0, 0],
        Nucs="14N",
        A=[15, 15, 80],
        AFrame=[0, 0, 0]
    )
    
    H0, mux, muy, muz = ham(sys)
    
    assert_matrices_close(H0, H0_ref, name="H0 (combined)")
    assert_matrices_close(mux, mux_ref, name="mux (combined)")
    assert_matrices_close(muy, muy_ref, name="muy (combined)")
    assert_matrices_close(muz, muz_ref, name="muz (combined)")


def test_ham_highspin():
    """Test 9: High-spin S=5/2 with ZFS."""
    mat_data = loadmat(DATA_DIR / "ref_ham_highspin.mat")
    H0_ref = mat_to_torch(mat_data["H9_0"])
    mux_ref = mat_to_torch(mat_data["mux9"])
    muy_ref = mat_to_torch(mat_data["muy9"])
    muz_ref = mat_to_torch(mat_data["muz9"])
    
    sys = SpinSystem(
        S=5/2,
        g=[2.0, 2.0, 2.0],
        D=[-200, -200, 400]  # MHz
    )
    
    H0, mux, muy, muz = ham(sys)
    
    assert_matrices_close(H0, H0_ref, name="H0 (high-spin)")
    assert_matrices_close(mux, mux_ref, name="mux (high-spin)")
    assert_matrices_close(muy, muy_ref, name="muy (high-spin)")
    assert_matrices_close(muz, muz_ref, name="muz (high-spin)")


def test_ham_tilted_frame():
    """Test 10: Tilted g-tensor frame with rotation."""
    mat_data = loadmat(DATA_DIR / "ref_ham_tilted.mat")
    H0_ref = mat_to_torch(mat_data["H10_0"])
    mux_ref = mat_to_torch(mat_data["mux10"])
    muy_ref = mat_to_torch(mat_data["muy10"])
    muz_ref = mat_to_torch(mat_data["muz10"])
    
    sys = SpinSystem(
        S=1/2,
        g=[2.0, 2.1, 2.2],
        gFrame=[np.pi/6, np.pi/4, np.pi/3]  # Euler angles in radians
    )
    
    H0, mux, muy, muz = ham(sys)
    
    assert_matrices_close(H0, H0_ref, name="H0 (tilted frame)")
    assert_matrices_close(mux, mux_ref, name="mux (tilted frame)")
    assert_matrices_close(muy, muy_ref, name="muy (tilted frame)")
    assert_matrices_close(muz, muz_ref, name="muz (tilted frame)")


if __name__ == "__main__":
    # Run all tests
    pytest.main([__file__, "-v"])
