"""
Extended Hamiltonian validation against MATLAB EasySpin.

Reference data: tests/data/ref_ham_ext.mat, generated by
tests/data/generate_ref_hamiltonians_ext.m.  Each case mirrors one EasySpin
test in EasySpin/tests/ham_*.m: it stores the EasySpin ``Sys`` struct (with
every random input frozen), the field-independent Hamiltonian and moment
operators from ``ham(Sys)``, ``ham(Sys,B0)`` when a field is used, and the
individual interaction term(s) the EasySpin test exercises.

All comparisons are element-wise (rtol 1e-10, atol 1e-9 MHz) — torchspin and
EasySpin use the same product-basis ordering (electrons, nuclei, OAMs; mS
descending), so no eigenvalue fallback is needed.
"""

from pathlib import Path

import numpy as np
import pytest
import torch
from scipy.io import loadmat

from torchspin.spinsystem import SpinSystem
from torchspin import (ham, ham_zf, ham_hf, ham_ee, ham_nq, ham_nn, ham_nz,
                       ham_ez, ham_ezho, ham_cf, ham_so, ham_oz)

DATA_DIR = Path(__file__).parent.parent.parent / "tests" / "data"
REF_FILE = DATA_DIR / "ref_ham_ext.mat"

RTOL = 1e-10
ATOL = 1e-9

# Cases that expose a genuine torchspin/EasySpin discrepancy.  Kept as xfail so
# the suite stays green while the discrepancy is visible.
XFAIL = {}  # scalar-D semantics fixed in SpinSystem (2026-09-01); nothing pending


# ---------------------------------------------------------------------------
# Loading helpers
# ---------------------------------------------------------------------------

def _load_cases():
    if not REF_FILE.exists():
        pytest.skip(f"Reference data not found: {REF_FILE}")
    mat = loadmat(str(REF_FILE), squeeze_me=True, struct_as_record=False)
    cases = mat['cases']
    if not isinstance(cases, np.ndarray):
        cases = np.array([cases])
    return {str(c.name): c for c in cases.ravel()}


_CASES = None


def get_cases():
    global _CASES
    if _CASES is None:
        _CASES = _load_cases()
    return _CASES


def _fields(obj):
    return list(obj._fieldnames)


def _arr(x):
    """MATLAB value -> float64 ndarray (scalars become 0-d)."""
    return np.asarray(x, dtype=np.float64)


def sys_from_matlab(ms) -> SpinSystem:
    """Convert an EasySpin ``Sys`` struct (mat_struct) to a SpinSystem."""
    f = _fields(ms)
    kw = {}

    S = _arr(ms.S)
    S_list = [float(S)] if S.ndim == 0 else [float(s) for s in S]
    kw['S'] = S_list
    n_e = len(S_list)

    if 'Nucs' in f:
        kw['Nucs'] = str(ms.Nucs)

    # Simple pass-through tensors
    for name in ('g', 'D', 'A', 'ee', 'Q', 'nn', 'sigma', 'gnscale'):
        if name in f:
            kw[name] = _arr(getattr(ms, name))

    # EasySpin D = [D1; D2] (nElectrons x 1 column, one scalar D per electron).
    # squeeze_me drops the column shape; restore it for n_e = 2 where a 1-D
    # length-2 vector would otherwise read as [D E].
    if 'D' in kw and kw['D'].ndim == 1 and kw['D'].size == n_e and n_e in (2, 3):
        kw['D'] = kw['D'].reshape(n_e, 1)

    # EasySpin: g as one isotropic value per electron, e.g. g = [2 2].
    # SpinSystem only recognizes scalar, (3,), (n_e,3) or full forms.
    if 'g' in kw and kw['g'].ndim == 1 and kw['g'].size == n_e and n_e != 3:
        kw['g'] = np.repeat(kw['g'].reshape(n_e, 1), 3, axis=1)

    # EasySpin stores a one-scalar-per-pair ee column; SpinSystem accepts
    # (nPairs,) directly but a MATLAB (n,1) squeezes to (n,), fine.
    if 'ee' in kw and kw['ee'].ndim == 0:
        kw['ee'] = kw['ee'].reshape(1)

    # Nuclear-nuclear scalar shorthand (EasySpin: isotropic J for the pair)
    if 'nn' in kw and kw['nn'].ndim == 0:
        kw['nn'] = np.array([[float(kw['nn'])] * 3])
    if 'nn' in kw and kw['nn'].ndim == 1 and kw['nn'].size == 3:
        # ambiguous: EasySpin resolves (1 x nPairs) column vs (1 x 3) principal
        # by number of pairs; here nPairs == 3 means one scalar per pair.
        n_n = len(kw.get('Nucs', '').split(',')) if kw.get('Nucs') else 0
        n_pairs = n_n * (n_n - 1) // 2
        if n_pairs == 3:
            kw['nn'] = np.repeat(kw['nn'].reshape(3, 1), 3, axis=1)
        else:
            kw['nn'] = kw['nn'].reshape(1, 3)

    # EasySpin: Q = [Qx Qy Qz] for a single nucleus; SpinSystem keeps a 1-D Q
    # as-is and ham_nq then indexes it as 2-D.
    if 'Q' in kw and kw['Q'].ndim == 1 and kw['Q'].size == 3:
        kw['Q'] = kw['Q'].reshape(1, 3)
    # EasySpin: scalar gnscale for a single nucleus.
    if 'gnscale' in kw and kw['gnscale'].ndim == 0:
        kw['gnscale'] = kw['gnscale'].reshape(1)

    # EasySpin: sigma = [sx sy sz] for a single nucleus (same gap as Q).
    if 'sigma' in kw and kw['sigma'].ndim == 1 and kw['sigma'].size == 3:
        kw['sigma'] = kw['sigma'].reshape(1, 3)

    # Frames.  SpinSystem normalizes 1-D gFrame/DFrame/AFrame/eeFrame but not
    # QFrame/sigmaFrame/nnFrame, so reshape the single-row shorthand here.
    for name in ('gFrame', 'DFrame', 'AFrame', 'eeFrame', 'QFrame', 'nnFrame',
                 'sigmaFrame'):
        if name in f:
            v = _arr(getattr(ms, name))
            if name in ('QFrame', 'sigmaFrame', 'nnFrame') and v.ndim == 1:
                v = v.reshape(1, 3)
            kw[name] = v

    # Orbital angular momentum
    if 'L' in f:
        L = _arr(ms.L)
        kw['L'] = [float(L)] if L.ndim == 0 else [float(l) for l in L]
        if 'gL' in f:
            gL = _arr(ms.gL)
            kw['gL'] = [float(gL)] if gL.ndim == 0 else [float(x) for x in gL]
        if 'soc' in f:
            soc = _arr(ms.soc)
            if soc.ndim == 0:
                soc = soc.reshape(1, 1)
            elif soc.ndim == 1:
                # MATLAB (n,1) column squeezes to (n,): one order per electron
                soc = soc.reshape(-1, 1) if len(kw['L']) > 1 else soc.reshape(1, -1)
            kw['soc'] = soc
        for k in range(1, 13):
            key = f'CF{k}'
            if key in f:
                kw[key] = _arr(getattr(ms, key)).reshape(len(kw['L']), 2 * k + 1)

    # Stevens operator coefficients B2..B8 -> B list [k=2,4,6,8]
    b_keys = [k for k in f if k.startswith('B') and k[1:].isdigit()]
    bf_keys = [k for k in f if k.startswith('B') and k.endswith('Frame')]
    if b_keys or bf_keys:
        kmax = max([int(k[1:]) for k in b_keys] +
                   [int(k[1:-5]) for k in bf_keys])
        nslots = kmax // 2
        B = [None] * nslots
        BF = [None] * nslots
        for key in b_keys:
            k = int(key[1:])
            v = _arr(getattr(ms, key)).reshape(n_e, 2 * k + 1)
            B[k // 2 - 1] = torch.tensor(v)
        for key in bf_keys:
            k = int(key[1:-5])
            v = _arr(getattr(ms, key)).reshape(-1, 3)
            BF[k // 2 - 1] = torch.tensor(v)
        kw['B'] = B
        if any(x is not None for x in BF):
            kw['BFrame'] = BF

    # Higher-order Zeeman: Ham{lB}{lS}{l}
    ham_keys = [k for k in f if k.startswith('Ham')]
    if ham_keys:
        kw['Ham'] = {key[3:]: _arr(getattr(ms, key)).reshape(1, -1)
                     for key in ham_keys}

    return SpinSystem(**kw)


# ---------------------------------------------------------------------------
# Comparison
# ---------------------------------------------------------------------------

def assert_close(torch_mat, matlab_mat, name):
    a = torch_mat.detach().cpu().numpy()
    if hasattr(matlab_mat, 'toarray'):      # scipy sparse (EasySpin sparse output)
        matlab_mat = matlab_mat.toarray()
    b = np.asarray(matlab_mat)
    if b.ndim == 0:
        b = b.reshape(1, 1)
    assert a.shape == b.shape, f"{name}: shape {a.shape} vs MATLAB {b.shape}"
    diff = np.abs(a - b)
    scale = max(np.max(np.abs(b)), 1.0)
    max_diff = float(np.max(diff)) if diff.size else 0.0
    assert max_diff <= ATOL + RTOL * scale, (
        f"{name}: max |diff| = {max_diff:.3e} (scale {scale:.3e})")


def _B0(case):
    return [float(x) for x in _arr(case.B0).ravel()]


# Map from stored matrix field -> callable(sys, case) producing the torchspin
# counterpart.  H0/mux/muy/muz/H are handled generically.
_TERM_BUILDERS = {
    'Hzf':     lambda s, c: ham_zf(s),
    'Hhf':     lambda s, c: ham_hf(s),
    'Hhf_e2n2': lambda s, c: ham_hf(s, [2], [2]),
    'Hee':     lambda s, c: ham_ee(s),
    'Hee_12':  lambda s, c: ham_ee(s, [1, 2]),
    'Hee_13':  lambda s, c: ham_ee(s, [1, 3]),
    'Hee_23':  lambda s, c: ham_ee(s, [2, 3]),
    'Hnq':     lambda s, c: ham_nq(s),
    'Hnq_2':   lambda s, c: ham_nq(s, [2]),
    'Hnn':     lambda s, c: ham_nn(s),
    'Hnn_12':  lambda s, c: ham_nn(s, [1, 2]),
    'Hnn_13':  lambda s, c: ham_nn(s, [1, 3]),
    'Hnn_23':  lambda s, c: ham_nn(s, [2, 3]),
    'Hnz':     lambda s, c: ham_nz(s, _B0(c)),
    'Hnz_1':   lambda s, c: ham_nz(s, _B0(c), [1]),
    'Hnz_2':   lambda s, c: ham_nz(s, _B0(c), [2]),
    'Hez':     lambda s, c: ham_ez(s, _B0(c)),
    'mux_e':   lambda s, c: ham_ez(s)[0],
    'muy_e':   lambda s, c: ham_ez(s)[1],
    'muz_e':   lambda s, c: ham_ez(s)[2],
    'mux_e2':  lambda s, c: ham_ez(s, None, [2])[0],
    'muy_e2':  lambda s, c: ham_ez(s, None, [2])[1],
    'muz_e2':  lambda s, c: ham_ez(s, None, [2])[2],
    'mux_n':   lambda s, c: ham_nz(s)[0],
    'muy_n':   lambda s, c: ham_nz(s)[1],
    'muz_n':   lambda s, c: ham_nz(s)[2],
    'Hezho':   lambda s, c: ham_ezho(s, _B0(c)),
    'G0':      lambda s, c: ham_ezho(s)[0],
    'G1x':     lambda s, c: ham_ezho(s)[1][0],
    'G1y':     lambda s, c: ham_ezho(s)[1][1],
    'G1z':     lambda s, c: ham_ezho(s)[1][2],
    'Hcf':     lambda s, c: ham_cf(s),
    'Hso':     lambda s, c: ham_so(s),
    'Hoz':     lambda s, c: ham_oz(s, _B0(c)),
}

_META_FIELDS = {'name', 'Sys', 'B0', 'note', 'note_ham'}


def _case_names():
    try:
        return sorted(get_cases().keys())
    except Exception:  # pragma: no cover - missing .mat handled in test body
        return []


# Historical note: before 2026-09-01 torchspin ham() omitted the higher-order
# Zeeman terms (never called ham_ezho) and SpinSystem defaulted g to gfree even
# when Ham110/Ham112 replaced the ordinary Zeeman term.  Both fixed.


def _has_ho_zeeman(case):
    return any(f.startswith('Ham') for f in _fields(case.Sys))


def _check_generic(sys, case):
    """ham(sys) -> (H0, mux, muy, muz) and ham(sys, B0) against the reference."""
    fields = _fields(case)
    if 'H0' in fields and np.asarray(case.mux).dtype != object:
        H0, mux, muy, muz = ham(sys)
        assert_close(H0, case.H0, 'H0')
        assert_close(mux, case.mux, 'mux')
        assert_close(muy, case.muy, 'muy')
        assert_close(muz, case.muz, 'muz')
    if 'H' in fields:
        assert_close(ham(sys, _B0(case)), case.H, 'H(B0)')


@pytest.mark.parametrize("case_name", _case_names())
def test_ham_ext(case_name):
    """Individual interaction terms and (for ordinary systems) the full ham()."""
    case = get_cases()[case_name]
    if case_name in XFAIL:
        pytest.xfail(XFAIL[case_name])

    sys = sys_from_matlab(case.Sys)
    fields = _fields(case)

    # Full-Hamiltonian checks for systems with Ham* terms live in
    # test_ham_ext_ho_zeeman_full (known discrepancy).
    if not _has_ho_zeeman(case):
        _check_generic(sys, case)

    for fld in fields:
        if fld in _META_FIELDS or fld in ('H0', 'mux', 'muy', 'muz', 'H'):
            continue
        builder = _TERM_BUILDERS.get(fld)
        assert builder is not None, f"no torchspin builder for field {fld}"
        assert_close(builder(sys, case), getattr(case, fld), fld)


@pytest.mark.parametrize(
    "case_name", [n for n in _case_names() if _has_ho_zeeman(get_cases()[n])])
def test_ham_ext_ho_zeeman_full(case_name):
    """ham()/ham(B0) for systems with Sys.Ham* terms (ham_ezho folded into ham())."""
    case = get_cases()[case_name]
    _check_generic(sys_from_matlab(case.Sys), case)


def test_reference_case_count():
    """Guard: the reference set should keep its full breadth."""
    assert len(get_cases()) >= 80
