"""
Validate garlic fast-motion (tcorr > 0) against MATLAB EasySpin references.

Reference data in tests/data/:
  - garlic_fastmotion_tcorr.mat   : nitroxide-like 14N, tcorr=2e-9 s
  - garlic_fastmotion_multinuc.mat: 14N + 1H, tcorr=1e-9 s

Both files store .x (field axis, mT) and .y (first-derivative spectrum) arrays
generated by the MATLAB scripts in tests/garlic_fastmotion_tcorr.m and
tests/garlic_fastmotion_multinuc.m.

A values are converted from mT to MHz using:
    A_MHz = A_mT * GFREE * BMAGN / PLANCK * 1e-9
"""

import math
from pathlib import Path

import numpy as np
import pytest
import torch

try:
    from scipy.io import loadmat
    SCIPY_AVAILABLE = True
except ImportError:
    SCIPY_AVAILABLE = False

from torchspin.spinsystem import SpinSystem
from torchspin.experiment import Experiment
from torchspin.garlic import garlic
from torchspin.constants import GFREE, BMAGN, PLANCK

# ---------------------------------------------------------------------------
# Constants / helpers
# ---------------------------------------------------------------------------

DATA_DIR = Path(__file__).parent.parent.parent / "tests" / "data"

#: MHz per mT using EasySpin-compatible GFREE constant
_MT_TO_MHZ = GFREE * BMAGN / PLANCK * 1e-9  # MHz/mT


def _cosine_similarity(a: np.ndarray, b: np.ndarray) -> float:
    """Cosine similarity between two normalized spectra."""
    an = a / np.abs(a).max()
    bn = b / np.abs(b).max()
    return float(np.dot(an, bn) / (np.linalg.norm(an) * np.linalg.norm(bn)))


def _require_mat(filename: str):
    """Skip test if scipy or .mat file unavailable."""
    if not SCIPY_AVAILABLE:
        pytest.skip("scipy not installed")
    path = DATA_DIR / filename
    if not path.exists():
        pytest.skip(f"Reference file not found: {path}")
    return path


# ---------------------------------------------------------------------------
# Test: garlic_fastmotion_tcorr
# ---------------------------------------------------------------------------
# From tests/garlic_fastmotion_tcorr.m:
#   Spins.g = [2.0088 2.0061 2.0027]
#   Spins.Nucs = '14N'
#   Spins.A = unitconvert([5.8 5.8 30.8]/10, 'mT->MHz')
#   Spins.tcorr = 2e-9
#   Exp.mwFreq = 9.7; Exp.Range = [341 350]  (nPoints default=1024, Harmonic default=1)

_A14N_TCORR = np.array([5.8, 5.8, 30.8]) / 10 * _MT_TO_MHZ   # MHz


class TestGarlicFastmotionTcorr:
    """Nitroxide-like 14N, tcorr = 2e-9 s."""

    @pytest.fixture(scope="class")
    def ref(self):
        path = _require_mat("garlic_fastmotion_tcorr.mat")
        d = loadmat(str(path), squeeze_me=True, struct_as_record=False)["data"]
        return d.x, d.y  # field axis (mT), spectrum

    @pytest.fixture(scope="class")
    def result(self):
        sys = SpinSystem(
            S=[0.5],
            g=[2.0088, 2.0061, 2.0027],
            Nucs="14N",
            A=_A14N_TCORR,
            lw=[0.0, 0.0],
        )
        sys.tcorr = 2e-9
        exp = Experiment(mwFreq=9.7, Range=[341.0, 350.0], nPoints=1024, Harmonic=1)
        return garlic(sys, exp)

    def test_field_axis_matches(self, ref, result):
        """Field axis should match MATLAB's within float tolerance."""
        x_ref, _ = ref
        x_py, _ = result
        np.testing.assert_allclose(
            x_py.numpy(), x_ref, atol=1e-6,
            err_msg="Field axis does not match MATLAB reference"
        )

    def test_spectrum_cosine_similarity(self, ref, result):
        """Spectrum shape must have cosine similarity ≥ 0.999 with MATLAB."""
        _, y_ref = ref
        _, y_py = result
        cs = _cosine_similarity(y_py.numpy(), y_ref)
        assert cs >= 0.999, (
            f"garlic_fastmotion_tcorr: cosine similarity {cs:.4f} < 0.999"
        )

    def test_spectrum_finite(self, result):
        _, y_py = result
        assert torch.isfinite(y_py).all()

    def test_derivative_integrates_to_zero(self, result):
        """First-derivative spectrum should integrate to ~0."""
        _, y_py = result
        integral = y_py.sum().item()
        assert abs(integral) < y_py.abs().max().item() * 50, (
            f"Derivative integral not ~0: {integral:.4e}"
        )


# ---------------------------------------------------------------------------
# Test: garlic_fastmotion_multinuc
# ---------------------------------------------------------------------------
# From tests/garlic_fastmotion_multinuc.m:
#   Spins.g = [2.0088 2.0061 2.0027]
#   Spins.Nucs = '14N,1H'
#   Spins.A = unitconvert([5.8 5.8 30.8; -3 -3 10]/10, 'mT->MHz')
#   Spins.tcorr = 1e-9
#   Exp.mwFreq = 9.7; Exp.Range = [343 348]

_A14N_MN = np.array([5.8, 5.8, 30.8]) / 10 * _MT_TO_MHZ
_A1H_MN  = np.array([-3.0, -3.0, 10.0]) / 10 * _MT_TO_MHZ


class TestGarlicFastmotionMultinuc:
    """14N + 1H two-nucleus fast-motion, tcorr = 1e-9 s."""

    @pytest.fixture(scope="class")
    def ref(self):
        path = _require_mat("garlic_fastmotion_multinuc.mat")
        d = loadmat(str(path), squeeze_me=True, struct_as_record=False)["data"]
        # This file only stores .y (no .x); reconstruct from known Exp.Range
        y = d.y
        x = np.linspace(343.0, 348.0, len(y))
        return x, y

    @pytest.fixture(scope="class")
    def result(self):
        sys = SpinSystem(
            S=[0.5],
            g=[2.0088, 2.0061, 2.0027],
            Nucs="14N,1H",
            A=[list(_A14N_MN), list(_A1H_MN)],
            lw=[0.0, 0.0],
        )
        sys.tcorr = 1e-9
        exp = Experiment(mwFreq=9.7, Range=[343.0, 348.0], nPoints=1024, Harmonic=1)
        return garlic(sys, exp)

    def test_spectrum_cosine_similarity(self, ref, result):
        """Spectrum shape must have cosine similarity ≥ 0.999 with MATLAB."""
        _, y_ref = ref
        _, y_py = result
        cs = _cosine_similarity(y_py.numpy(), y_ref)
        assert cs >= 0.999, (
            f"garlic_fastmotion_multinuc: cosine similarity {cs:.4f} < 0.999"
        )

    def test_spectrum_finite(self, result):
        _, y_py = result
        assert torch.isfinite(y_py).all()

    def test_output_shape(self, result):
        x_py, y_py = result
        assert x_py.shape == (1024,)
        assert y_py.shape == (1024,)
