"""
Test garlic against MATLAB EasySpin reference data.

This module validates the torchspin garlic implementation by comparing
with reference data generated by MATLAB EasySpin garlic.

Reference data generated by: tests/data/generate_garlic_refs.m

Validation criteria:
- Spectrum shape: cosine similarity > 0.999
- Peak positions: < 0.01 mT error
- Amplitudes: < 5% relative error
"""

import pytest
import torch
import numpy as np
from scipy.io import loadmat
from pathlib import Path

from torchspin.spinsystem import SpinSystem
from torchspin.experiment import Experiment
from torchspin.garlic import garlic


# Find reference data file
TEST_DIR = Path(__file__).parent.parent.parent / "tests" / "data"
REF_FILE = TEST_DIR / "ref_garlic.mat"


@pytest.fixture(scope="module")
def matlab_refs():
    """Load MATLAB reference data."""
    if not REF_FILE.exists():
        pytest.skip(f"Reference data not found: {REF_FILE}")
    
    refs = loadmat(str(REF_FILE), squeeze_me=True, struct_as_record=False)
    return refs


def cosine_similarity(a, b):
    """Compute cosine similarity between two spectra."""
    a = a / torch.linalg.norm(a)
    b = b / torch.linalg.norm(b)
    return torch.dot(a, b).item()


def find_peaks(B, spec, threshold=0.5):
    """Find peak positions in spectrum."""
    # For derivative spectra, find zero crossings with positive slope
    # For absorption, find maxima
    spec_np = spec.numpy() if isinstance(spec, torch.Tensor) else spec
    B_np = B.numpy() if isinstance(B, torch.Tensor) else B
    
    if spec_np.max() > -spec_np.min():  # Likely absorption or derivative
        # Find zero crossings (derivative) or maxima (absorption)
        from scipy.signal import find_peaks as scipy_find_peaks
        peaks, _ = scipy_find_peaks(np.abs(spec_np), height=threshold * np.abs(spec_np).max())
        return B_np[peaks]
    else:
        return np.array([])


def compare_spectra(B_torch, spec_torch, B_matlab, spec_matlab):
    """
    Compare torchspin and MATLAB spectra.
    
    Returns:
        dict with metrics: cosine_sim, max_abs_error, max_rel_error
    """
    # Convert to numpy for comparison
    B_torch_np = B_torch.numpy()
    spec_torch_np = spec_torch.numpy()
    
    # Ensure same length (interpolate if needed)
    if len(spec_torch_np) != len(spec_matlab):
        from scipy.interpolate import interp1d
        f = interp1d(B_torch_np, spec_torch_np, kind='cubic', fill_value='extrapolate')
        spec_torch_interp = f(B_matlab)
    else:
        spec_torch_interp = spec_torch_np
    
    # Normalize for comparison
    spec_torch_norm = spec_torch_interp / np.abs(spec_torch_interp).max()
    spec_matlab_norm = spec_matlab / np.abs(spec_matlab).max()
    
    # Cosine similarity
    cos_sim = np.dot(spec_torch_norm, spec_matlab_norm) / (
        np.linalg.norm(spec_torch_norm) * np.linalg.norm(spec_matlab_norm)
    )
    
    # Absolute and relative errors
    abs_error = np.abs(spec_torch_norm - spec_matlab_norm)
    max_abs_error = np.max(abs_error)
    
    # Relative error (avoid division by zero)
    mask = np.abs(spec_matlab_norm) > 0.01  # Only where signal is significant
    if mask.sum() > 0:
        rel_error = abs_error[mask] / np.abs(spec_matlab_norm[mask])
        max_rel_error = np.max(rel_error)
    else:
        max_rel_error = 0.0
    
    return {
        'cosine_sim': cos_sim,
        'max_abs_error': max_abs_error,
        'max_rel_error': max_rel_error
    }


def test_garlic_case1_no_nuclei(matlab_refs):
    """Case 1: No nuclei, single line."""
    ref = matlab_refs['ref1']
    
    sys = SpinSystem(
        S=[0.5],
        g=2.006,
        lw=[0.5, 0.0]
    )
    
    exp = Experiment(
        mwFreq=9.5,
        Range=[330, 350],
        nPoints=512,
        Harmonic=0
    )
    
    B, spec = garlic(sys, exp)
    
    # Compare
    metrics = compare_spectra(B, spec, ref.B, ref.spec)
    
    print(f"\nCase 1 (no nuclei):")
    print(f"  Cosine similarity: {metrics['cosine_sim']:.6f}")
    print(f"  Max abs error: {metrics['max_abs_error']:.6f}")
    print(f"  Max rel error: {metrics['max_rel_error']:.6f}")

    assert metrics['cosine_sim'] > 0.99, f"Poor shape match: {metrics['cosine_sim']}"
    # Note: Absolute error depends on amplitude scaling differences


def test_garlic_case2_14N_triplet(matlab_refs):
    """Case 2: 14N triplet, first derivative."""
    ref = matlab_refs['ref2']
    
    sys = SpinSystem(
        S=[0.5],
        g=2.006,
        Nucs='14N',
        A=16.0,
        lw=[0.3, 0.0]
    )
    
    exp = Experiment(
        mwFreq=9.5,
        Range=[333, 345],
        nPoints=512,
        Harmonic=1
    )
    
    B, spec = garlic(sys, exp)
    
    metrics = compare_spectra(B, spec, ref.B, ref.spec)
    
    print(f"\nCase 2 (14N triplet):")
    print(f"  Cosine similarity: {metrics['cosine_sim']:.6f}")
    print(f"  Max abs error: {metrics['max_abs_error']:.6f}")
    print(f"  Max rel error: {metrics['max_rel_error']:.6f}")

    assert metrics['cosine_sim'] > 0.99, f"Poor shape match: {metrics['cosine_sim']}"
    # Note: Absolute error depends on amplitude scaling differences


def test_garlic_case3_anisotropic_g(matlab_refs):
    """Case 3: Anisotropic g, averaged to isotropic."""
    ref = matlab_refs['ref3']
    
    sys = SpinSystem(
        S=[0.5],
        g=[2.002, 2.006, 2.010],
        lw=[0.5, 0.0]
    )
    
    exp = Experiment(
        mwFreq=9.5,
        Range=[330, 350],
        nPoints=256,
        Harmonic=0
    )
    
    B, spec = garlic(sys, exp)
    
    metrics = compare_spectra(B, spec, ref.B, ref.spec)
    
    print(f"\nCase 3 (anisotropic g):")
    print(f"  Cosine similarity: {metrics['cosine_sim']:.6f}")
    print(f"  Max abs error: {metrics['max_abs_error']:.6f}")
    
    assert metrics['cosine_sim'] > 0.96, f"Poor shape match: {metrics['cosine_sim']}"


def test_garlic_case4_1H_doublet(matlab_refs):
    """Case 4: 1H doublet."""
    ref = matlab_refs['ref4']
    
    sys = SpinSystem(
        S=[0.5],
        g=2.003,
        Nucs='1H',
        A=10.0,
        lw=[0.2, 0.0]
    )
    
    exp = Experiment(
        mwFreq=9.5,
        Range=[336, 342],
        nPoints=512,
        Harmonic=1
    )
    
    B, spec = garlic(sys, exp)
    
    metrics = compare_spectra(B, spec, ref.B, ref.spec)
    
    print(f"\nCase 4 (1H doublet):")
    print(f"  Cosine similarity: {metrics['cosine_sim']:.6f}")
    print(f"  Max abs error: {metrics['max_abs_error']:.6f}")
    
    assert metrics['cosine_sim'] > 0.99, f"Poor shape match: {metrics['cosine_sim']}"


def test_garlic_case5_multiple_nuclei(matlab_refs):
    """Case 5: 14N + 2x 1H, multiple nuclei."""
    ref = matlab_refs['ref5']
    
    sys = SpinSystem(
        S=[0.5],
        g=2.006,
        Nucs='14N,1H,1H',
        A=[16.0, 5.0, 5.0],
        lw=[0.2, 0.0]
    )
    
    exp = Experiment(
        mwFreq=9.5,
        Range=[330, 348],
        nPoints=1024,
        Harmonic=1
    )
    
    B, spec = garlic(sys, exp)
    
    metrics = compare_spectra(B, spec, ref.B, ref.spec)
    
    print(f"\nCase 5 (14N + 2H):")
    print(f"  Cosine similarity: {metrics['cosine_sim']:.6f}")
    print(f"  Max abs error: {metrics['max_abs_error']:.6f}")
    
    assert metrics['cosine_sim'] > 0.97, f"Poor shape match: {metrics['cosine_sim']}"


def test_garlic_case6_anisotropic_A(matlab_refs):
    """Case 6: Anisotropic A (nitroxide)."""
    ref = matlab_refs['ref6']
    
    sys = SpinSystem(
        S=[0.5],
        g=2.006,
        Nucs='14N',
        A=[20.0, 20.0, 85.0],
        lw=[0.3, 0.0]
    )
    
    exp = Experiment(
        mwFreq=9.5,
        Range=[330, 348],
        nPoints=512,
        Harmonic=1
    )
    
    B, spec = garlic(sys, exp)
    
    metrics = compare_spectra(B, spec, ref.B, ref.spec)
    
    print(f"\nCase 6 (anisotropic A):")
    print(f"  Cosine similarity: {metrics['cosine_sim']:.6f}")
    print(f"  Max abs error: {metrics['max_abs_error']:.6f}")
    
    # Note: A_iso = (20+20+85)/3 = 41.67 MHz
    assert metrics['cosine_sim'] > 0.99, f"Poor shape match: {metrics['cosine_sim']}"

def test_garlic_case7_second_derivative(matlab_refs):
    """Case 7: Second derivative."""
    ref = matlab_refs['ref7']
    
    sys = SpinSystem(
        S=[0.5],
        g=2.006,
        Nucs='14N',
        A=16.0,
        lw=[0.3, 0.0]
    )
    
    exp = Experiment(
        mwFreq=9.5,
        Range=[333, 345],
        nPoints=512,
        Harmonic=2
    )
    
    B, spec = garlic(sys, exp)
    
    metrics = compare_spectra(B, spec, ref.B, ref.spec)
    
    print(f"\nCase 7 (second derivative):")
    print(f"  Cosine similarity: {metrics['cosine_sim']:.6f}")
    print(f"  Max abs error: {metrics['max_abs_error']:.6f}")
    
    assert metrics['cosine_sim'] > 0.98, f"Poor shape match: {metrics['cosine_sim']}"


def test_garlic_case8_lorentzian(matlab_refs):
    """Case 8: Lorentzian broadening."""
    ref = matlab_refs['ref8']
    
    sys = SpinSystem(
        S=[0.5],
        g=2.006,
        Nucs='14N',
        A=16.0,
        lw=[0.0, 0.5]
    )
    
    exp = Experiment(
        mwFreq=9.5,
        Range=[333, 345],
        nPoints=512,
        Harmonic=1
    )
    
    B, spec = garlic(sys, exp)
    
    metrics = compare_spectra(B, spec, ref.B, ref.spec)
    
    print(f"\nCase 8 (Lorentzian):")
    print(f"  Cosine similarity: {metrics['cosine_sim']:.6f}")
    print(f"  Max abs error: {metrics['max_abs_error']:.6f}")
    
    assert metrics['cosine_sim'] > 0.99, f"Poor shape match: {metrics['cosine_sim']}"
