"""
MATLAB cross-validation of multi-electron g strain and per-electron D strain.

Reference: tests/data/strain_ref_multielectron.mat, generated by
tests/data/generate_strain_multielectron_refs.m (EasySpin pepper).

Covers the parts of EasySpin resfields.m that were NotImplementedError in
torchspin before 2026-09-01: the non-simple g strain branch
(gA2 = sum_e |m(kSzL_e)| gStrainMatrix_e.^2), and getdstrainops for
several electrons, tilted D frames and a D/E correlation coefficient.
"""

from pathlib import Path

import numpy as np
import pytest
import torch
from scipy.io import loadmat

from torchspin.spinsystem import SpinSystem
from torchspin.experiment import Experiment, Options
from torchspin.pepper import pepper

REF_FILE = Path(__file__).parent.parent.parent / "tests" / "data" / "strain_ref_multielectron.mat"


@pytest.fixture(scope="module")
def cases():
    if not REF_FILE.exists():
        pytest.skip(f"Reference data not found: {REF_FILE}")
    refs = loadmat(str(REF_FILE), squeeze_me=True, struct_as_record=False)
    return {str(c.name): c for c in np.atleast_1d(refs['cases'])}


def _fields(o):
    return getattr(o, '_fieldnames', [])


def _get(o, name, default=None):
    return getattr(o, name) if name in _fields(o) else default


def sys_from_mat(S) -> SpinSystem:
    Sv = np.atleast_1d(np.asarray(S.S, dtype=float))
    kw = {'S': Sv.tolist()}
    n_e = len(kw['S'])
    g = np.asarray(S.g, dtype=float)
    if g.ndim == 1 and g.size == n_e and n_e > 1:
        g = np.repeat(g.reshape(n_e, 1), 3, axis=1)
    kw['g'] = g.tolist() if g.ndim else float(g)
    for name in ('gFrame', 'gStrain', 'DFrame', 'DStrain'):
        v = _get(S, name)
        if v is not None:
            v = np.asarray(v, dtype=float)
            kw[name] = v.tolist()
    D = _get(S, 'D')
    if D is not None:
        D = np.asarray(D, dtype=float)
        if D.ndim == 1 and D.size == 2 and n_e == 1:
            kw['D'] = [D.tolist()]           # [[D, E]]
        else:
            kw['D'] = D.tolist()             # (n_e, 2) rows of [D, E]
    r = _get(S, 'DStrainCorr')
    if r is not None:
        r = np.atleast_1d(np.asarray(r, dtype=float))
        kw['DStrainCorr'] = r.tolist()
    ee = _get(S, 'ee')
    if ee is not None:
        kw['ee'] = [float(ee)]
    kw['lw'] = [0.0, 0.0]
    return SpinSystem(**kw)


def exp_from_mat(E) -> Experiment:
    return Experiment(mwFreq=float(E.mwFreq), Range=np.asarray(E.Range, dtype=float).tolist(),
                      nPoints=int(E.nPoints), Harmonic=int(E.Harmonic))


def cosine(a, b):
    a = np.asarray(a, dtype=float); b = np.asarray(b, dtype=float)
    return float(np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b)))


# Spectrum-level thresholds (after PORT_SPEC_2 1.2/1.3: first-principles intensity,
# level-pair transition bookkeeping, EasySpin's strain summation on the fine grid).
THRESHOLDS = {
    'two_spinhalf_gstrain_both': 0.999,
    'two_spinhalf_gstrain_second': 0.999,
    'triplet_dstrain_tilted': 0.999,
    'two_triplets_dstrain_corr': 0.999,
    'triplet_dstrain_corr': 0.999,
}


@pytest.mark.parametrize("name", list(THRESHOLDS))
def test_multielectron_strain_vs_matlab(cases, name):
    c = cases[name]
    sys = sys_from_mat(c.Sys)
    exp = exp_from_mat(c.Exp)
    opt = Options(GridSize=[int(c.Opt.GridSize), 4], Verbosity=0)  # EasySpin scalar N == [N 4]
    B, spc = pepper(sys, exp, opt)
    spc = spc.numpy()
    ref = np.asarray(c.spc, dtype=float)
    assert np.all(np.isfinite(spc))
    cs = cosine(spc, ref)
    assert cs > THRESHOLDS[name], f"{name}: cosine {cs:.5f}"
    ratio = np.abs(spc).max() / np.abs(ref).max()
    assert abs(ratio - 1) < 0.03, f"{name}: amplitude ratio {ratio:.4f}"


def test_gstrain_multielectron_no_longer_raises():
    """Regression: gStrain for two electrons used to raise NotImplementedError."""
    sys = SpinSystem(S=[0.5, 0.5], g=[[2.0, 2.05, 2.15], [1.98, 2.02, 2.1]],
                     gStrain=[[0.01, 0.02, 0.03], [0.02, 0.01, 0.015]], ee=[300.0], lw=[0, 0])
    exp = Experiment(mwFreq=9.5, Range=[290, 380], nPoints=256, Harmonic=1)
    B, spc = pepper(sys, exp, Options(GridSize=7))
    assert torch.isfinite(spc).all() and spc.abs().max() > 0


def test_dstrain_two_electrons_shape():
    sys = SpinSystem(S=[1, 1], g=[2.0, 2.0], D=[[500, 60], [700, -90]],
                     DStrain=[[50, 10], [40, 20]], DStrainCorr=[0.5, -0.3], ee=[50.0])
    assert tuple(sys.DStrain.shape) == (2, 2)
    assert sys.DStrainCorr == [0.5, -0.3]
