"""
MATLAB cross-validation of garlic's EasySpin-ported line engine.

Reference: tests/data/ref_garlic_exact.mat, generated by
tests/data/generate_garlic_exact_refs.m with EasySpin.  The cases mirror
EasySpin's own garlic tests (garlic_perturb, garlic_manynuclei,
garlic_modamp, garlic_freqsweep_exact, garlic_hfsign, garlic_equivnuclei,
garlic_temperature) plus a few extra ones (63Cu exact vs perturb2, full
A/g matrices, fast motion with perturb5 / field modulation).

Each test compares the whole spectrum by cosine similarity and, where the
reference stores them, the resonance positions to sub-µT accuracy.
"""

from pathlib import Path

import numpy as np
import pytest
import torch
from scipy.io import loadmat

from torchspin.spinsystem import SpinSystem
from torchspin.experiment import Experiment, Options
from torchspin.garlic import garlic

REF_FILE = Path(__file__).parent.parent.parent / "tests" / "data" / "ref_garlic_exact.mat"


@pytest.fixture(scope="module")
def cases():
    if not REF_FILE.exists():
        pytest.skip(f"Reference data not found: {REF_FILE} (run generate_garlic_exact_refs.m)")
    refs = loadmat(str(REF_FILE), squeeze_me=True, struct_as_record=False)
    out = {}
    for c in np.atleast_1d(refs['cases']):
        out[str(c.name)] = c
    return out


def _fields(obj):
    return getattr(obj, '_fieldnames', [])


def _get(obj, name, default=None):
    return getattr(obj, name) if name in _fields(obj) else default


def _to_list(v):
    a = np.atleast_1d(np.asarray(v, dtype=float))
    return a.tolist()


def sys_from_mat(S) -> SpinSystem:
    kw = {'S': [0.5]}
    g = _get(S, 'g')
    if g is not None:
        g = np.asarray(g, dtype=float)
        kw['g'] = g.tolist() if g.ndim else float(g)
    else:
        from torchspin.constants import GFREE
        kw['g'] = GFREE  # EasySpin default gfree
    nucs = _get(S, 'Nucs')
    if nucs is not None:
        kw['Nucs'] = str(nucs)
        A = np.asarray(_get(S, 'A'), dtype=float)
        kw['A'] = A.tolist() if A.ndim else float(A)
        n = _get(S, 'n')
        if n is not None:
            kw['n'] = [int(v) for v in np.atleast_1d(n)]
    for name in ('lw', 'lwpp'):
        v = _get(S, name)
        if v is not None:
            v = _to_list(v)
            kw[name] = v if len(v) == 2 else [v[0], 0.0]
    if 'lw' not in kw and 'lwpp' not in kw:
        kw['lw'] = [0.0, 0.0]
    tc = _get(S, 'tcorr')
    if tc is not None:
        kw['tcorr'] = float(tc)
    return SpinSystem(**kw)


def exp_from_mat(E) -> Experiment:
    kw = {}
    for name in ('mwFreq', 'nPoints', 'Harmonic', 'ModAmp', 'Field', 'Temperature'):
        v = _get(E, name)
        if v is not None:
            kw[name] = int(v) if name in ('nPoints', 'Harmonic') else float(v)
    for name in ('Range', 'CenterSweep', 'mwRange'):
        v = _get(E, name)
        if v is not None:
            kw[name] = _to_list(v)
    if 'Harmonic' not in kw:
        # EasySpin auto-harmonic: 1 for broadened field sweeps, 0 for frequency sweeps
        kw['Harmonic'] = 0 if 'mwRange' in kw else 1
    return Experiment(**kw)


def opt_from_mat(O) -> Options:
    m = _get(O, 'Method') if O is not None else None
    return Options(Method=str(m)) if m is not None else Options()


def cosine(a, b):
    a = np.asarray(a, dtype=float); b = np.asarray(b, dtype=float)
    return float(np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b)))


def run_case(c):
    sys = sys_from_mat(c.Sys)
    exp = exp_from_mat(c.Exp)
    opt = opt_from_mat(_get(c, 'Opt'))
    x, y = garlic(sys, exp, opt)
    return sys, exp, opt, x.numpy(), y.numpy()


# ---------------------------------------------------------------------------
# garlic_perturb: 3 equivalent 1H, A = 600 MHz — every method vs EasySpin
# ---------------------------------------------------------------------------
@pytest.mark.parametrize("method", ['perturb1', 'perturb2', 'perturb3', 'perturb4', 'perturb5', 'exact'])
def test_perturb_methods(cases, method):
    c = cases[f'perturb_{method}']
    _, _, _, x, y = run_case(c)
    np.testing.assert_allclose(x, np.asarray(c.x, dtype=float), rtol=0, atol=1e-9)
    cs = cosine(y, c.y)
    assert cs > 0.9999, f"{method}: cosine {cs:.6f}"
    # Resonance positions (mT) — the solver output itself
    from torchspin.garlic import _resonance_lines, _isotropic_g
    sys = sys_from_mat(c.Sys)
    giso = _isotropic_g(sys)
    from torchspin.constants import PLANCK, BMAGN
    central = 9.7e9 * PLANCK / (BMAGN * giso) * 1e3
    order = {'exact': 0, 'perturb1': 1, 'perturb2': 2, 'perturb3': 3, 'perturb4': 4, 'perturb5': 5}[method]
    pos, _, _, _ = _resonance_lines(sys, giso, central, True, 9.7e9, None, order, 1e-12, 15, False)
    ref = np.sort(np.asarray(c.resfields, dtype=float).reshape(-1))
    np.testing.assert_allclose(np.sort(pos), ref, rtol=0, atol=1e-6)  # µT


def test_perturb_scale_matches_easyspin(cases):
    """Absolute intensity convention (TransitionRate·dBdE) matches EasySpin."""
    c = cases['perturb_exact']
    _, _, _, _, y = run_case(c)
    ratio = np.abs(y).max() / np.abs(np.asarray(c.y)).max()
    assert abs(ratio - 1) < 1e-3, f"amplitude ratio {ratio}"


# ---------------------------------------------------------------------------
# garlic_manynuclei: 1H n=5 + 14N n=4 (equivcouple reduction, 300 lines)
# ---------------------------------------------------------------------------
def test_manynuclei(cases):
    c = cases['manynuclei']
    _, _, _, x, y = run_case(c)
    assert cosine(y, c.y) > 0.9999
    ref = np.sort(np.asarray(c.resfields, dtype=float).reshape(-1))
    sys = sys_from_mat(c.Sys)
    from torchspin.garlic import _resonance_lines, _isotropic_g
    from torchspin.constants import PLANCK, BMAGN
    giso = _isotropic_g(sys)
    central = 9.7e9 * PLANCK / (BMAGN * giso) * 1e3
    pos, amps, _, _ = _resonance_lines(sys, giso, central, True, 9.7e9, None, 0, 1e-12, 15, False)
    pos = np.asarray(pos.detach()) if hasattr(pos, 'detach') else np.asarray(pos)
    assert pos.size == ref.size == 300
    np.testing.assert_allclose(np.sort(pos), ref, rtol=0, atol=1e-6)
    assert abs(amps.sum() - 1.0) < 1e-12


# ---------------------------------------------------------------------------
# garlic_modamp: pseudo-modulation
# ---------------------------------------------------------------------------
@pytest.mark.parametrize("name", ['modamp', 'modamp_h2', 'fastmotion_modamp'])
def test_field_modulation(cases, name):
    c = cases[name]
    _, _, _, x, y = run_case(c)
    np.testing.assert_allclose(x, np.asarray(c.x, dtype=float), rtol=0, atol=1e-9)
    cs = cosine(y, c.y)
    assert cs > 0.999, f"{name}: cosine {cs:.6f}"


# ---------------------------------------------------------------------------
# Frequency sweeps
# ---------------------------------------------------------------------------
@pytest.mark.parametrize("name", ['freqsweep_exact', 'freqsweep_pt2'])
def test_frequency_sweep(cases, name):
    c = cases[name]
    _, _, _, x, y = run_case(c)
    np.testing.assert_allclose(x, np.asarray(c.x, dtype=float), rtol=0, atol=1e-12)
    cs = cosine(y, c.y)
    assert cs > 0.9999, f"{name}: cosine {cs:.6f}"


# ---------------------------------------------------------------------------
# garlic_hfsign: spectrum invariant under the sign of A
# ---------------------------------------------------------------------------
def test_hyperfine_sign_invariance(cases):
    c = cases['hfsign']
    sys_pos = sys_from_mat(c.Sys)
    exp = exp_from_mat(c.Exp)
    opt = opt_from_mat(c.Opt)
    sys_neg = SpinSystem(S=[0.5], g=sys_pos.g.clone(), Nucs='1H', A=-100.0, lwpp=[0.1, 0.0])
    _, ypos = garlic(sys_pos, exp, opt)
    _, yneg = garlic(sys_neg, exp, opt)
    np.testing.assert_allclose(ypos.numpy(), yneg.numpy(), rtol=1e-3, atol=1e-6 * float(ypos.abs().max()))
    assert cosine(ypos.numpy(), c.y) > 0.9999
    assert cosine(yneg.numpy(), c.yneg) > 0.9999


# ---------------------------------------------------------------------------
# garlic_equivnuclei: n=4 vs four explicit 1H — same integrated spectrum
# ---------------------------------------------------------------------------
def test_equivalent_nuclei_vs_explicit(cases):
    c = cases['equivnuclei']
    exp = exp_from_mat(c.Exp)
    opt = opt_from_mat(c.Opt)
    sys1 = sys_from_mat(c.Sys)
    sys2 = SpinSystem(S=[0.5], Nucs='1H,1H,1H,1H', A=[10, 10, 10, 10], lw=[0, 0.02])
    _, y1 = garlic(sys1, exp, opt)
    _, y2 = garlic(sys2, exp, opt)
    assert abs(y1.sum() / y2.sum() - 1) < 1e-4
    assert cosine(y1.numpy(), c.y) > 0.9999
    assert cosine(y2.numpy(), c.y2) > 0.9999


# ---------------------------------------------------------------------------
# garlic_temperature: Boltzmann polarization scale factor
# ---------------------------------------------------------------------------
def test_temperature_polarization(cases):
    c = cases['temperature']
    sys = sys_from_mat(c.Sys)
    expT = exp_from_mat(c.Exp)
    exp0 = Experiment(mwFreq=expT.mwFreq, Range=expT.Range, nPoints=expT.nPoints, Harmonic=expT.Harmonic)
    _, yT = garlic(sys, expT)
    _, y0 = garlic(sys, exp0)
    ratio_py = float(yT.abs().max() / y0.abs().max())
    ratio_ml = float(np.abs(c.y).max() / np.abs(c.y0).max())
    assert abs(ratio_py / ratio_ml - 1) < 1e-6, (ratio_py, ratio_ml)
    assert cosine(yT.numpy(), c.y) > 0.9999


# ---------------------------------------------------------------------------
# 63Cu, A = 150 MHz: exact vs second-order (second-order shifts are visible)
# ---------------------------------------------------------------------------
def test_cu_exact_and_perturb2(cases):
    c = cases['cu_exact']
    sys = sys_from_mat(c.Sys)
    exp = exp_from_mat(c.Exp)
    _, ye = garlic(sys, exp, Options(Method='exact'))
    _, yp = garlic(sys, exp, Options(Method='perturb2'))
    assert cosine(ye.numpy(), c.y) > 0.9999
    assert cosine(yp.numpy(), c.y_pt2) > 0.9999
    from torchspin.garlic import _resonance_lines, _isotropic_g
    from torchspin.constants import PLANCK, BMAGN
    giso = _isotropic_g(sys)
    central = 9.5e9 * PLANCK / (BMAGN * giso) * 1e3
    pos, _, _, _ = _resonance_lines(sys, giso, central, True, 9.5e9, None, 0, 1e-12, 15, False)
    np.testing.assert_allclose(np.sort(pos), np.sort(np.asarray(c.resfields, dtype=float)), atol=1e-6)


# ---------------------------------------------------------------------------
# Full A and g matrices: isotropic parts via eigenvalues
# ---------------------------------------------------------------------------
def test_full_matrices(cases):
    c = cases['fullAg']
    g = np.asarray(c.Sys.g, dtype=float)
    A = np.asarray(c.Sys.A, dtype=float)
    sys = SpinSystem(S=[0.5], g=g.tolist(), Nucs='1H', A=A.tolist(), lw=[0, 0.05])
    exp = exp_from_mat(c.Exp)
    _, y = garlic(sys, exp)
    assert cosine(y.numpy(), c.y) > 0.9999
    from torchspin.garlic import _resonance_lines, _isotropic_g
    from torchspin.constants import PLANCK, BMAGN
    giso = _isotropic_g(sys)
    central = 9.5e9 * PLANCK / (BMAGN * giso) * 1e3
    pos, _, _, _ = _resonance_lines(sys, giso, central, True, 9.5e9, None, 0, 1e-12, 15, False)
    np.testing.assert_allclose(np.sort(pos), np.sort(np.asarray(c.resfields, dtype=float)), atol=1e-6)


# ---------------------------------------------------------------------------
# Fast motion with 5th-order perturbation and Gaussian residual broadening
# ---------------------------------------------------------------------------
def test_fastmotion_perturb5(cases):
    c = cases['fastmotion_pt5']
    _, _, _, x, y = run_case(c)
    cs = cosine(y, c.y)
    assert cs > 0.999, f"cosine {cs:.6f}"
