"""pepper feature validation against EasySpin (PORT_SPEC_2 items 3.3, 3.7, 3.8 + mwPhase).

Reference: tests/data/ref_pepper_features.mat, generated by
tests/data/generate_pepper_features_refs.m (EasySpin 6, MATLAB R2024b), mirroring
EasySpin's pepper_modamp, pepper_dispersion_fieldsweep, pepper_separatecomponents,
pepper_iso_cu, pepper_iso_customabund, pepper_iso_twonucs and pepper_isotopes_two_Si.
"""
from pathlib import Path

import numpy as np
import pytest
from scipy.io import loadmat

from torchspin.tests.test_pepper_matlab_validation_ext2 import (
    sys_from_mat, exp_from_mat, opt_from_mat, cosine, _get)
from torchspin.pepper import pepper

REF = Path(__file__).resolve().parents[2] / 'tests' / 'data' / 'ref_pepper_features.mat'


@pytest.fixture(scope='module')
def cases():
    if not REF.exists():
        pytest.skip(f'reference file missing: {REF}')
    m = loadmat(REF, squeeze_me=True, struct_as_record=False)
    return {str(c.name): c for c in np.atleast_1d(m['cases'])}


def _case_names():
    if not REF.exists():
        return []
    m = loadmat(REF, squeeze_me=True, struct_as_record=False)
    return [str(c.name) for c in np.atleast_1d(m['cases'])]


# name -> (cosine threshold, amplitude tolerance, reason)
LOOSE = {}


def _run(c):
    if _get(c, 'Sys2') is not None:
        systems = [sys_from_mat(c.Sys), sys_from_mat(c.Sys2)]
        return pepper(systems, exp_from_mat(c.Exp, c.Sys), opt_from_mat(c.Opt))
    return pepper(sys_from_mat(c.Sys), exp_from_mat(c.Exp, c.Sys), opt_from_mat(c.Opt))


@pytest.mark.parametrize('name', _case_names())
def test_pepper_feature_vs_matlab(cases, name):
    c = cases[name]
    B, spc = _run(c)
    B = B.detach().cpu().numpy(); spc = spc.detach().cpu().numpy()
    ref = np.asarray(c.spc, dtype=float)
    ref_B = np.asarray(c.B, dtype=float)
    assert np.allclose(B, ref_B, rtol=0, atol=1e-6 * max(1.0, abs(ref_B).max())), 'field axis differs'
    cos_thr, amp_tol, _ = LOOSE.get(name, (0.999, 0.02, ''))
    if ref.ndim == 2:
        assert spc.shape == ref.shape, (spc.shape, ref.shape)
        for k in range(ref.shape[0]):
            assert cosine(spc[k], ref[k]) > cos_thr, (name, k, cosine(spc[k], ref[k]))
            amp = abs(spc[k]).max() / abs(ref[k]).max()
            assert abs(amp - 1) < amp_tol, (name, k, amp)
    else:
        assert spc.shape == ref.shape
        assert cosine(spc, ref) > cos_thr, (name, cosine(spc, ref))
        amp = abs(spc).max() / abs(ref).max()
        assert abs(amp - 1) < amp_tol, (name, amp)
