"""MATLAB cross-validation for salt (powder ENDOR) against EasySpin references.

References generated by ``tests/data/generate_salt_refs.m`` (EasySpin, MATLAB
R2024b). Each ``.mat`` holds ``data.x`` (RF axis, MHz), ``data.y`` (spectrum),
and the generating ``Sys``/``Exp``/``Opt`` structs.

EasySpin salt semantics targeted here (fixed-field ENDOR):
  - ``Exp.Field``  — static field, mT
  - ``Exp.Range``  — RF frequency window, MHz
  - ``Exp.nPoints``— points across ``Exp.Range`` (default 1024)
  - ``Sys.lwEndor``— Gaussian FWHM (MHz)
  - ``Exp.ExciteWidth`` + ``Exp.mwFreq`` — optional orientation selection
"""

import os

import numpy as np
import pytest

try:
    from scipy.io import loadmat
except ImportError:  # pragma: no cover
    loadmat = None

from torchspin.experiment import Experiment, Options
from torchspin.salt import salt
from torchspin.spinsystem import SpinSystem

DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "tests", "data")


def _load_data(filename):
    if loadmat is None:
        pytest.skip("scipy not installed")
    path = os.path.join(DATA_DIR, filename)
    if not os.path.exists(path):
        pytest.skip(f"Reference file not found: {path}")
    return loadmat(path, simplify_cells=True)["data"]


def _cosine(a, b):
    a = np.asarray(a, dtype=float).ravel()
    b = np.asarray(b, dtype=float).ravel()
    n = min(len(a), len(b))
    a, b = a[:n], b[:n]
    return float(abs(np.dot(a, b)) /
                 (np.linalg.norm(a) * np.linalg.norm(b) + 1e-30))


def _run_salt_endor(sys, field_mT, rf_range, n_points, lw, mw_freq,
                    excite_width=None, grid_size=31):
    """Run torchspin salt in fixed-field EasySpin-equivalent mode."""
    exp = Experiment(Field=field_mT, mwFreq=mw_freq)
    if excite_width is not None:
        exp.ExciteWidth = excite_width
    opt = Options()
    opt.GridSize = grid_size
    x, y = salt(sys, exp, opt,
                freq_range=tuple(rf_range), n_points=n_points, lw_mhz=lw)
    return np.asarray(x), np.asarray(y)


def _interp_to_ref(x_py, y_py, x_ref):
    return np.interp(x_ref, x_py, y_py)


# ---------------------------------------------------------------------------
# Case 1: rhombic g + 1H axial A, X-band (salt_invariance_axial1 base)
# ---------------------------------------------------------------------------


def test_salt_1H_rhombicg_cosine():
    """1H powder ENDOR, rhombic g: cosine vs MATLAB >= 0.999."""
    ref = _load_data("salt_1H_rhombicg.mat")
    sys = SpinSystem(S=[0.5], g=[[2.0, 2.01, 2.02]],
                     Nucs='1H', A=[[-2.0, -2.0, 4.0]])
    x, y = _run_salt_endor(sys, field_mT=326.5, rf_range=(10, 20),
                           n_points=len(np.ravel(ref['y'])), lw=0.1,
                           mw_freq=9.7)
    y_ref = np.asarray(ref['y'], dtype=float).ravel()
    x_ref = np.asarray(ref['x'], dtype=float).ravel()
    y_i = _interp_to_ref(x, y, x_ref)
    cos = _cosine(y_i, y_ref)
    assert cos > 0.999, f"salt 1H rhombic-g cosine {cos:.4f} < 0.999"


# ---------------------------------------------------------------------------
# Case 2: tilted AFrame (rotational invariance partner of case 1)
# ---------------------------------------------------------------------------


def test_salt_1H_aframe_cosine():
    """1H powder ENDOR with tilted AFrame: cosine vs MATLAB >= 0.999."""
    ref = _load_data("salt_1H_aframe.mat")
    aframe = [v * np.pi / 180 for v in (23.0, 72.0, -12.0)]
    sys = SpinSystem(S=[0.5], g=[[2.0, 2.01, 2.02]],
                     Nucs='1H', A=[[-2.0, -2.0, 4.0]],
                     AFrame=[aframe])
    x, y = _run_salt_endor(sys, field_mT=326.5, rf_range=(10, 20),
                           n_points=len(np.ravel(ref['y'])), lw=0.1,
                           mw_freq=9.7)
    y_ref = np.asarray(ref['y'], dtype=float).ravel()
    x_ref = np.asarray(ref['x'], dtype=float).ravel()
    y_i = _interp_to_ref(x, y, x_ref)
    cos = _cosine(y_i, y_ref)
    assert cos > 0.999, f"salt 1H AFrame cosine {cos:.4f} < 0.999"


# ---------------------------------------------------------------------------
# Case 3: 14N + quadrupole, W-band, full excitation
# ---------------------------------------------------------------------------


def test_salt_14N_Wband_cosine():
    """14N + quadrupole W-band powder ENDOR: cosine vs MATLAB >= 0.90."""
    ref = _load_data("salt_14N_Wband.mat")
    sys = SpinSystem(S=[0.5], g=[[2.2, 2.2, 2.0]],
                     Nucs='14N', A=[[4.0, 4.0, 5.0]],
                     Q=[[0.84, 0.84, -1.68]],
                     HStrain=[1.0, 1.0, 1.0])
    x, y = _run_salt_endor(sys, field_mT=3394.0, rf_range=(0, 35),
                           n_points=4096, lw=0.1, mw_freq=95.0,
                           grid_size=50)
    y_ref = np.asarray(ref['y'], dtype=float).ravel()
    x_ref = np.asarray(ref['x'], dtype=float).ravel()
    y_i = _interp_to_ref(x, y, x_ref)
    cos = _cosine(y_i, y_ref)
    assert cos > 0.999, f"salt 14N W-band cosine {cos:.4f} < 0.999"


# ---------------------------------------------------------------------------
# Cases 4+5: 14N W-band orientation selection (gz vs gx)
# ---------------------------------------------------------------------------


def test_salt_14N_orisel_gz_cosine():
    """14N W-band, ExciteWidth=3 GHz at gz: cosine vs MATLAB >= 0.90."""
    ref = _load_data("salt_14N_orisel_gz.mat")
    sys = SpinSystem(S=[0.5], g=[[2.2, 2.2, 2.0]],
                     Nucs='14N', A=[[4.0, 4.0, 5.0]],
                     Q=[[0.84, 0.84, -1.68]],
                     HStrain=[1.0, 1.0, 1.0])
    x, y = _run_salt_endor(sys, field_mT=3394.0, rf_range=(0, 35),
                           n_points=4096, lw=0.1, mw_freq=95.0,
                           excite_width=3e3, grid_size=50)
    y_ref = np.asarray(ref['y'], dtype=float).ravel()
    x_ref = np.asarray(ref['x'], dtype=float).ravel()
    y_i = _interp_to_ref(x, y, x_ref)
    cos = _cosine(y_i, y_ref)
    assert cos > 0.99, f"salt 14N orisel-gz cosine {cos:.4f} < 0.99"


def test_salt_14N_orisel_gx_cosine():
    """14N W-band, ExciteWidth=3 GHz at gx (mwFreq=104.51): cosine >= 0.90."""
    ref = _load_data("salt_14N_orisel_gx.mat")
    sys = SpinSystem(S=[0.5], g=[[2.2, 2.2, 2.0]],
                     Nucs='14N', A=[[4.0, 4.0, 5.0]],
                     Q=[[0.84, 0.84, -1.68]],
                     HStrain=[1.0, 1.0, 1.0])
    x, y = _run_salt_endor(sys, field_mT=3394.0, rf_range=(0, 35),
                           n_points=4096, lw=0.1, mw_freq=104.51,
                           excite_width=3e3, grid_size=50)
    y_ref = np.asarray(ref['y'], dtype=float).ravel()
    x_ref = np.asarray(ref['x'], dtype=float).ravel()
    y_i = _interp_to_ref(x, y, x_ref)
    cos = _cosine(y_i, y_ref)
    assert cos > 0.99, f"salt 14N orisel-gx cosine {cos:.4f} < 0.99"


# ---------------------------------------------------------------------------
# Case 6: axial g + 1H, X-band orientation selection
# ---------------------------------------------------------------------------


def test_salt_1H_orisel_axialg_cosine():
    """1H X-band, axial g, ExciteWidth=100 MHz at g=2.1: cosine >= 0.90."""
    ref = _load_data("salt_1H_orisel_axialg.mat")
    from torchspin.constants import PLANCK, BMAGN
    field = 9.5e9 * PLANCK / BMAGN / 2.1 * 1e3  # mT
    sys = SpinSystem(S=[0.5], g=[[2.0, 2.0, 2.2]],
                     Nucs='1H', A=[[2.5, 2.5, 7.0]])
    x, y = _run_salt_endor(sys, field_mT=field, rf_range=(8, 18),
                           n_points=len(np.ravel(ref['y'])), lw=0.02,
                           mw_freq=9.5, excite_width=100.0, grid_size=181)
    y_ref = np.asarray(ref['y'], dtype=float).ravel()
    x_ref = np.asarray(ref['x'], dtype=float).ravel()
    y_i = _interp_to_ref(x, y, x_ref)
    cos = _cosine(y_i, y_ref)
    assert cos > 0.99, f"salt 1H orisel axial-g cosine {cos:.4f} < 0.99"


# ---------------------------------------------------------------------------
# Case 7: two nuclei (1H + 14N), isotropic g
# ---------------------------------------------------------------------------


def test_salt_twonuc_cosine():
    """1H + 14N powder ENDOR, isotropic g: cosine vs MATLAB >= 0.999."""
    ref = _load_data("salt_1H14N_twonuc.mat")
    sys = SpinSystem(S=[0.5], g=[[2.0023, 2.0023, 2.0023]],
                     Nucs=['1H', '14N'],
                     A=[[2.0, 2.0, 6.0], [1.0, 1.0, 3.0]],
                     Q=[[0.0, 0.0, 0.0], [-0.5, -0.5, 1.0]])
    x, y = _run_salt_endor(sys, field_mT=350.0, rf_range=(0, 25),
                           n_points=len(np.ravel(ref['y'])), lw=0.1,
                           mw_freq=9.8)
    y_ref = np.asarray(ref['y'], dtype=float).ravel()
    x_ref = np.asarray(ref['x'], dtype=float).ravel()
    y_i = _interp_to_ref(x, y, x_ref)
    cos = _cosine(y_i, y_ref)
    assert cos > 0.999, f"salt two-nucleus cosine {cos:.4f} < 0.999"


# ---------------------------------------------------------------------------
# Case 8: S=3/2 + 1H high-spin
# ---------------------------------------------------------------------------


def test_salt_S32_cosine():
    """S=3/2 + 1H powder ENDOR: cosine vs MATLAB >= 0.90."""
    ref = _load_data("salt_S32_1H.mat")
    sys = SpinSystem(S=[1.5], g=[[2.0, 2.0, 2.0]],
                     D=[[500.0, 0.0]],
                     Nucs='1H', A=[[3.0, 3.0, 8.0]])
    x, y = _run_salt_endor(sys, field_mT=350.0, rf_range=(5, 25),
                           n_points=len(np.ravel(ref['y'])), lw=0.1,
                           mw_freq=9.8)
    y_ref = np.asarray(ref['y'], dtype=float).ravel()
    x_ref = np.asarray(ref['x'], dtype=float).ravel()
    y_i = _interp_to_ref(x, y, x_ref)
    cos = _cosine(y_i, y_ref)
    assert cos > 0.98, f"salt S=3/2 cosine {cos:.4f} < 0.98"


# ---------------------------------------------------------------------------
# Grid handling: [N_coarse, N_interp] GridSize and projection vs. reference
# ---------------------------------------------------------------------------


def test_salt_gridsize_interp_matches_reference_grid():
    """GridSize=[20, 5] (the reference's Opt.GridSize) reproduces MATLAB to
    cosine >= 0.9999: transitions are interpolated 5x on the orientation grid
    and projected as triangles (EasySpin salt.m), not binned as sticks."""
    ref = _load_data("salt_1H_rhombicg.mat")
    y_ref = np.asarray(ref['y'], dtype=float).ravel()
    sys = SpinSystem(S=[0.5], g=[[2.0, 2.01, 2.02]],
                     Nucs='1H', A=[[-2.0, -2.0, 4.0]])
    x, y = _run_salt_endor(sys, field_mT=326.5, rf_range=(10, 20),
                           n_points=y_ref.size, lw=0.1, mw_freq=9.7,
                           grid_size=[20, 5])
    y_i = _interp_to_ref(x, y, np.asarray(ref['x'], dtype=float).ravel())
    cos = _cosine(y_i, y_ref)
    assert cos > 0.9999, f"salt [20,5] cosine {cos:.5f} < 0.9999"
    coef = float(np.dot(y_i, y_ref) / np.dot(y_i, y_i))
    resid = np.abs(y_ref - coef * y_i) / np.abs(y_ref).max()
    assert resid.max() < 0.01, f"max normalized residual {resid.max():.4f} >= 0.01"


def test_salt_default_options_gridsize_list():
    """Default Options() carries GridSize=[19, 4]; salt must accept it."""
    sys = SpinSystem(S=[0.5], g=[[2.0, 2.01, 2.02]],
                     Nucs='1H', A=[[-2.0, -2.0, 4.0]])
    exp = Experiment(Field=326.5, mwFreq=9.7)
    x, y = salt(sys, exp, Options(), freq_range=(10, 20), n_points=256, lw_mhz=0.1)
    y = np.asarray(y)
    assert y.shape == (256,) and np.all(np.isfinite(y)) and y.max() > 0
