"""MATLAB cross-validation for spidyan against EasySpin references.

References generated by ``tests/data/generate_spidyan_refs.m`` (EasySpin,
MATLAB R2024b).  Each ``.mat`` holds ``data.t`` (µs), ``data.sig_re``,
``data.sig_im`` — the detected signal's real/imaginary parts, with detection
operators along the first axis for multi-operator cases.

Cases mirror EasySpin's ``tests/spidyan_*.m``.
"""

import os

import numpy as np
import pytest

try:
    from scipy.io import loadmat
except ImportError:  # pragma: no cover
    loadmat = None

from torchspin import SpinSystem
from torchspin.spidyan import spidyan, SpidyanOptions

DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "tests", "data")

CHIRP_PULSE = {
    'Type': 'quartersin/linear',
    'trise': 0.015,
    'tp': 0.1,
    'Flip': np.pi,
    'Frequency': [-100.0, 100.0],   # MHz
}


def _load_data(filename):
    if loadmat is None:
        pytest.skip("scipy not installed")
    path = os.path.join(DATA_DIR, filename)
    if not os.path.exists(path):
        pytest.skip(f"Reference file not found: {path}")
    return loadmat(path, simplify_cells=True)["data"]


def _cosine(a, b):
    a = np.asarray(a, dtype=float).ravel()
    b = np.asarray(b, dtype=float).ravel()
    n = min(len(a), len(b))
    a, b = a[:n], b[:n]
    na, nb = np.linalg.norm(a), np.linalg.norm(b)
    if na == 0 or nb == 0:
        return 0.0
    return float(abs(np.dot(a, b)) / (na * nb))


def _zsys(zeeman_freq_GHz=33.5, **extra):
    sys = SpinSystem(S=[0.5], g=[[2.0023, 2.0023, 2.0023]])
    sys.ZeemanFreq = zeeman_freq_GHz
    for k, v in extra.items():
        setattr(sys, k, v)
    return sys


# ---------------------------------------------------------------------------
# Case 1: S=1/2, chirp pulse pair, det z1 and +1 (spidyan_spinonehalf)
# ---------------------------------------------------------------------------


def test_spidyan_spinonehalf_cosine():
    """Chirp pi-pulse pair, <Sz> and <S+> detection: cosine >= 0.99."""
    ref = _load_data("spidyan_spinonehalf.mat")
    sys = _zsys()
    exp = {
        'Field': 1240.0,
        'mwFreq': 33.5,
        'Sequence': [dict(CHIRP_PULSE), 0.5, dict(CHIRP_PULSE)],
        'DetSequence': [1, 1, 1],
        'DetOperator': ['z1', '+1'],
        'DetFreq': [0.0, 33.5],
    }
    opt = SpidyanOptions(IntTimeStep=0.0001, SimFreq=32)
    t, sig, _ = spidyan(sys, exp, opt)
    sig = np.atleast_2d(np.asarray(sig))
    if sig.shape[0] > sig.shape[1]:
        sig = sig.T                     # → (nDet, nT)
    ref_re = np.atleast_2d(np.asarray(ref['sig_re'], dtype=float))
    # z1 channel (real)
    cos_z = _cosine(sig[0].real, ref_re[0])
    assert cos_z > 0.99, f"spinonehalf <Sz> cosine {cos_z:.4f} < 0.99"
    # +1 channel (compare real parts of the down-mixed transverse signal)
    cos_p = _cosine(sig[1].real, ref_re[1])
    assert cos_p > 0.99, f"spinonehalf <S+> cosine {cos_p:.4f} < 0.99"


# ---------------------------------------------------------------------------
# Case 2: electron-nucleus (1H, A=[8 45 45]) (spidyan_electronnucleus)
# ---------------------------------------------------------------------------


def test_spidyan_electronnucleus_cosine():
    """S=1/2 + 1H (A=[8,45,45] MHz), chirp pulse + delay: cosine >= 0.99."""
    ref = _load_data("spidyan_electronnucleus.mat")
    sys = SpinSystem(S=[0.5], g=[[2.00232, 2.00232, 2.00232]],
                     Nucs='1H', A=[[8.0, 45.0, 45.0]])
    exp = {
        'Field': 1195.0,
        'mwFreq': 33.5,
        'Sequence': [dict(CHIRP_PULSE), 0.5],
        'DetSequence': [1, 1],
        'DetOperator': ['z1'],
        'DetFreq': [0.0],
        'DetPhase': 0.0,
    }
    opt = SpidyanOptions(IntTimeStep=0.0001, SimFreq=32)
    t, sig, _ = spidyan(sys, exp, opt)
    cos = _cosine(np.asarray(sig).real.ravel(),
                  np.asarray(ref['sig_re'], dtype=float).ravel())
    assert cos > 0.99, f"electronnucleus cosine {cos:.4f} < 0.99"


# ---------------------------------------------------------------------------
# Case 3: S=3/2 with D=200 MHz (spidyan_highspin)
# ---------------------------------------------------------------------------


def test_spidyan_highspin_cosine():
    """S=3/2, D=200 MHz, chirp pulse + delay: cosine >= 0.99."""
    ref = _load_data("spidyan_highspin.mat")
    sys = SpinSystem(S=[1.5], g=[[2.00232, 2.00232, 2.00232]],
                     D=[[200.0, 0.0]])
    exp = {
        'Field': 1195.0,
        'mwFreq': 33.5,
        'Sequence': [dict(CHIRP_PULSE), 0.5],
        'DetSequence': [1, 1],
        'DetOperator': ['z1'],
        'DetPhase': 0.0,
    }
    opt = SpidyanOptions(IntTimeStep=0.0001, SimFreq=32)
    t, sig, _ = spidyan(sys, exp, opt)
    cos = _cosine(np.asarray(sig).real.ravel(),
                  np.asarray(ref['sig_re'], dtype=float).ravel())
    assert cos > 0.99, f"highspin cosine {cos:.4f} < 0.99"


# ---------------------------------------------------------------------------
# Case 4: two-step phase cycling (spidyan_phasecycling)
# ---------------------------------------------------------------------------


def test_spidyan_phasecycling_cosine():
    """[0,+1; pi,-1] phase cycle on 1st and 3rd pulse: cosine >= 0.99."""
    ref = _load_data("spidyan_phasecycling.mat")
    sys = _zsys()
    p = {'Type': 'rectangular', 'tp': 0.1, 'Flip': np.pi}
    p2 = dict(p, Phase=np.pi)
    pc = np.array([[0.0, 1.0], [np.pi, -1.0]])
    exp = {
        'Field': 1240.0,
        'mwFreq': 33.5,
        'Sequence': [p, p2, p],
        'DetSequence': [1],
        'PhaseCycle': [pc, None, pc],
        'DetOperator': ['z1'],
        'DetPhase': 0.0,
    }
    opt = SpidyanOptions(IntTimeStep=0.0001, SimFreq=32)
    t, sig, _ = spidyan(sys, exp, opt)
    cos = _cosine(np.asarray(sig).real.ravel(),
                  np.asarray(ref['sig_re'], dtype=float).ravel())
    assert cos > 0.99, f"phasecycling cosine {cos:.4f} < 0.99"


# ---------------------------------------------------------------------------
# Case 5: 1D indirect dimension varying pulse flip (spidyan_onedimensional)
# ---------------------------------------------------------------------------


def test_spidyan_onedimensional_cosine():
    """3-point sweep of first-pulse flip angle: per-step cosine >= 0.99."""
    ref = _load_data("spidyan_onedimensional.mat")
    sys = _zsys()
    p = {'Type': 'rectangular', 'tp': 0.1, 'Flip': np.pi}
    exp = {
        'Field': 1240.0,
        'mwFreq': 33.5,
        'Sequence': [p, 0.5, p],
        'DetSequence': [1],
        'nPoints': 3,
        'Dim1': ['p1.Flip', 0.05],
        'DetOperator': ['z1'],
        'DetPhase': 0.0,
    }
    opt = SpidyanOptions(IntTimeStep=0.0001, SimFreq=32)
    t, sig, _ = spidyan(sys, exp, opt)
    ref_re = np.atleast_2d(np.asarray(ref['sig_re'], dtype=float))
    if isinstance(sig, (list, tuple)):
        rows = [np.asarray(s).real.ravel() for s in sig]
    else:
        sig = np.asarray(sig)
        rows = [sig[i].real.ravel() for i in range(sig.shape[0])]
    assert len(rows) == ref_re.shape[0], \
        f"expected {ref_re.shape[0]} steps, got {len(rows)}"
    for i, row in enumerate(rows):
        cos = _cosine(row, ref_re[i])
        assert cos > 0.99, f"onedimensional step {i} cosine {cos:.4f} < 0.99"


# ---------------------------------------------------------------------------
# Case 6: two coupled electrons, J=0 (spidyan_electronelectron)
# ---------------------------------------------------------------------------


def test_spidyan_electronelectron_cosine():
    """Two S=1/2, J=0, chirp pulse + delay: cosine >= 0.99."""
    ref = _load_data("spidyan_electronelectron.mat")
    sys = SpinSystem(S=[0.5, 0.5],
                     g=[[2.00232, 2.00232, 2.00232],
                        [2.00232, 2.00232, 2.00232]],
                     ee=[0.0])
    exp = {
        'Field': 1195.0,
        'mwFreq': 33.5,
        'Sequence': [dict(CHIRP_PULSE), 0.5],
        'DetSequence': [1, 1],
        'DetFreq': 0.0,
        'DetPhase': 0.0,
    }
    opt = SpidyanOptions(IntTimeStep=0.0001, SimFreq=32)
    t, sig, _ = spidyan(sys, exp, opt)
    sig = np.atleast_2d(np.asarray(sig))
    if sig.shape[0] > sig.shape[1]:
        sig = sig.T
    ref_re = np.atleast_2d(np.asarray(ref['sig_re'], dtype=float))
    n_ch = min(sig.shape[0], ref_re.shape[0])
    for i in range(n_ch):
        cos = _cosine(sig[i].real, ref_re[i])
        assert cos > 0.99, f"electronelectron ch{i} cosine {cos:.4f} < 0.99"


# ---------------------------------------------------------------------------
# Case 7: T1/T2 relaxation during chirp + delay (spidyan_relaxation)
# ---------------------------------------------------------------------------


def test_spidyan_relaxation_cosine():
    """T1=1 µs, T2=0.4 µs relaxation, <Sz> detection: cosine >= 0.99."""
    ref = _load_data("spidyan_relaxation.mat")
    sys = _zsys(T1=1.0, T2=0.4)
    exp = {
        'Field': 1240.0,
        'mwFreq': 33.5,
        'Sequence': [dict(CHIRP_PULSE), 0.5],
        'DetSequence': [1, 1],
        'DetOperator': ['z1'],
        'DetFreq': [0.0],
        'DetPhase': 0.0,
    }
    opt = SpidyanOptions(IntTimeStep=0.0001, SimFreq=32, Relaxation=True)
    t, sig, _ = spidyan(sys, exp, opt)
    cos = _cosine(np.asarray(sig).real.ravel(),
                  np.asarray(ref['sig_re'], dtype=float).ravel())
    assert cos > 0.99, f"relaxation cosine {cos:.4f} < 0.99"
