"""
MATLAB validation tests for torchspin.endorfrq and torchspin.salt.

Reference data is generated by running tests/generate_endorfrq_refs.m in MATLAB
(EasySpin must be on the path).  Tests are skipped if the .mat files are absent.

Orientation convention mapping:
  MATLAB Exp.SampleFrame = [0, beta, 0]
  → field at phi=0, theta=beta in torchspin endorfrq()

Comparison metric for single-orientation ENDOR:
  - Match sorted frequency positions within ±1.0 MHz
  - Match number of significant lines (rel. intensity > 0.01)

Comparison metric for powder (salt):
  - Cosine similarity > 0.97 after interpolation to common grid
"""

import math
from pathlib import Path

import numpy as np
import pytest
import torch

try:
    from scipy.io import loadmat
    from scipy.interpolate import interp1d
    SCIPY_AVAILABLE = True
except ImportError:
    SCIPY_AVAILABLE = False

from torchspin.spinsystem import SpinSystem
from torchspin.experiment import Experiment, Options
from torchspin.endorfrq import endorfrq
from torchspin.salt import salt

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

DATA_DIR = Path(__file__).parent.parent.parent / "tests" / "data"


def _require_mat(filename: str):
    """Skip test if scipy or .mat file unavailable."""
    if not SCIPY_AVAILABLE:
        pytest.skip("scipy not installed")
    path = DATA_DIR / filename
    if not path.exists():
        pytest.skip(
            f"Reference file not found: {path}\n"
            "Run tests/generate_endorfrq_refs.m in MATLAB to generate it."
        )
    return path


def _cosine_similarity(a: np.ndarray, b: np.ndarray) -> float:
    a = a / np.abs(a).max()
    b = b / np.abs(b).max()
    return float(np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b)))


def _match_lines(
    ref_pos: np.ndarray,
    ref_int: np.ndarray,
    our_pos: np.ndarray,
    our_int: np.ndarray,
    int_threshold: float = 0.01,
    tol_mhz: float = 1.0,
) -> tuple[int, int]:
    """
    Count how many strong MATLAB lines have a torchspin match within tol_mhz.

    Returns
    -------
    n_matched : int
        Number of strong MATLAB lines matched.
    n_strong : int
        Total number of strong MATLAB lines.
    """
    if len(ref_int) == 0 or ref_int.max() == 0:
        return 0, 0
    strong_mask = ref_int / ref_int.max() > int_threshold
    strong_pos = ref_pos[strong_mask]
    n_matched = 0
    for p in strong_pos:
        if len(our_pos) > 0 and np.min(np.abs(our_pos.numpy() - p)) < tol_mhz:
            n_matched += 1
    return n_matched, int(strong_mask.sum())


# ---------------------------------------------------------------------------
# Case 1: S=1/2 + 1H, isotropic A=10 MHz, theta=0
# ---------------------------------------------------------------------------

class TestEndorfrqVsMatlab1H_Axial:
    """Compare endorfrq to MATLAB: 1H isotropic A=10 MHz, field along z."""

    def _load(self):
        path = _require_mat("endorfrq_ref_1H_axial.mat")
        data = loadmat(str(path))
        return data

    def _make_sys(self):
        return SpinSystem(S=[0.5], g=[[2.0, 2.0, 2.0]], Nucs=["1H"], A=[[10.0, 10.0, 10.0]])

    def test_line_count_matches(self):
        data = self._load()
        ref_pos = data["pos1"].ravel()
        ref_int = data["int1"].ravel()
        B_res = float(np.asarray(data["B_res"]).squeeze())
        mwFreq = float(np.asarray(data["mwFreq"]).squeeze())

        sys = self._make_sys()
        freqs, intens, _ = endorfrq(sys, B_res, phi=0.0, theta=0.0,
                                    freq_range=(0.0, 50.0))

        n_matched, n_strong = _match_lines(ref_pos, ref_int, freqs, intens)
        assert n_strong >= 1, "No strong MATLAB lines found"
        assert n_matched == n_strong, (
            f"Only {n_matched}/{n_strong} strong MATLAB lines matched "
            f"(pos={ref_pos}, ours={freqs.numpy()})"
        )

    def test_frequencies_within_1mhz(self):
        data = self._load()
        ref_pos = np.sort(data["pos1"].ravel())
        ref_int = data["int1"].ravel()
        B_res = float(np.asarray(data["B_res"]).squeeze())

        sys = self._make_sys()
        freqs, intens, _ = endorfrq(sys, B_res, phi=0.0, theta=0.0,
                                    freq_range=(0.0, 50.0))

        our_pos = np.sort(freqs.numpy())
        # All strong MATLAB lines within 1 MHz of a torchspin line
        strong_mask = ref_int / ref_int.max() > 0.01
        for p in ref_pos[strong_mask]:
            diffs = np.abs(our_pos - p)
            assert diffs.min() < 1.0, (
                f"MATLAB line at {p:.3f} MHz not matched (closest={diffs.min():.3f} MHz)"
            )


# ---------------------------------------------------------------------------
# Case 2: S=1/2 + 14N, isotropic A=30 MHz, theta=pi/3
# ---------------------------------------------------------------------------

class TestEndorfrqVsMatlab14N_Offaxis:
    """Compare endorfrq to MATLAB: 14N isotropic A=30 MHz, theta=pi/3."""

    def _load(self):
        path = _require_mat("endorfrq_ref_14N_offaxis.mat")
        return loadmat(str(path))

    def _make_sys(self):
        return SpinSystem(S=[0.5], g=[[2.0, 2.0, 2.0]], Nucs=["14N"], A=[[30.0, 30.0, 30.0]])

    def test_line_count_matches(self):
        data = self._load()
        ref_pos = data["pos2"].ravel()
        ref_int = data["int2"].ravel()
        B_res = float(np.asarray(data["B_res"]).squeeze())

        sys = self._make_sys()
        freqs, intens, _ = endorfrq(sys, B_res, phi=0.0, theta=math.pi / 3,
                                    freq_range=(0.0, 60.0))

        n_matched, n_strong = _match_lines(ref_pos, ref_int, freqs, intens)
        assert n_strong >= 2, "Expected at least 2 strong MATLAB lines for 14N"
        assert n_matched >= n_strong - 1, (
            f"Only {n_matched}/{n_strong} strong MATLAB lines matched"
        )

    def test_frequencies_within_1mhz(self):
        data = self._load()
        ref_pos = data["pos2"].ravel()
        ref_int = data["int2"].ravel()
        B_res = float(np.asarray(data["B_res"]).squeeze())

        sys = self._make_sys()
        freqs, intens, _ = endorfrq(sys, B_res, phi=0.0, theta=math.pi / 3,
                                    freq_range=(0.0, 60.0))

        our_pos = freqs.numpy()
        strong_mask = ref_int / ref_int.max() > 0.01
        for p in ref_pos[strong_mask]:
            diffs = np.abs(our_pos - p)
            assert diffs.min() < 1.0, (
                f"MATLAB line at {p:.3f} MHz not matched (closest={diffs.min():.3f} MHz)"
            )


# ---------------------------------------------------------------------------
# Case 3: S=1/2 + 1H, anisotropic A=[5 5 20] MHz, theta=pi/4
# ---------------------------------------------------------------------------

class TestEndorfrqVsMatlab1H_Aniso:
    """Compare endorfrq to MATLAB: 1H anisotropic A=[5,5,20] MHz, theta=pi/4."""

    def _load(self):
        path = _require_mat("endorfrq_ref_1H_aniso.mat")
        return loadmat(str(path))

    def _make_sys(self):
        return SpinSystem(S=[0.5], g=[[2.0, 2.0, 2.0]], Nucs=["1H"], A=[[5.0, 5.0, 20.0]])

    def test_frequencies_within_1mhz(self):
        data = self._load()
        ref_pos = data["pos3"].ravel()
        ref_int = data["int3"].ravel()
        B_res = float(np.asarray(data["B_res"]).squeeze())

        sys = self._make_sys()
        freqs, intens, _ = endorfrq(sys, B_res, phi=0.0, theta=math.pi / 4,
                                    freq_range=(0.0, 50.0))

        our_pos = freqs.numpy()
        strong_mask = ref_int / ref_int.max() > 0.01
        for p in ref_pos[strong_mask]:
            diffs = np.abs(our_pos - p)
            assert diffs.min() < 1.0, (
                f"MATLAB line at {p:.3f} MHz not matched (closest={diffs.min():.3f} MHz)"
            )


# ---------------------------------------------------------------------------
# Salt (powder ENDOR) — 1H
# ---------------------------------------------------------------------------

class TestSaltVsMatlab1H:
    """Compare salt powder ENDOR to MATLAB for 1H isotropic A=10 MHz."""

    def _load(self):
        path = _require_mat("salt_ref_1H.mat")
        return loadmat(str(path))

    def test_cosine_similarity(self):
        data = self._load()
        x_ref = data["x_salt1"].ravel()  # MHz
        y_ref = data["y_salt1"].ravel()

        sys = SpinSystem(S=[0.5], g=[[2.0, 2.0, 2.0]], Nucs=["1H"], A=[[10.0, 10.0, 10.0]])
        # Range must bracket the EPR resonance (~338.4 mT) for resfields to find it
        exp_salt = Experiment(mwFreq=9.5, Range=[330.0, 350.0], nPoints=256)

        x_our, y_our = salt(
            sys,
            exp_salt,
            opt=Options(GridSize=31, Verbosity=0),
            freq_range=(float(x_ref.min()), float(x_ref.max())),
            n_points=len(x_ref),
            lw_mhz=0.5,
        )

        x_our_np = x_our.numpy()
        y_our_np = y_our.numpy()

        if y_ref.max() == 0 or y_our_np.max() == 0:
            pytest.skip("One spectrum is all zeros; skipping cosine check")

        cos = _cosine_similarity(y_ref, y_our_np)
        assert cos > 0.92, f"Cosine similarity {cos:.4f} < 0.92"


# ---------------------------------------------------------------------------
# Salt (powder ENDOR) — 14N
# ---------------------------------------------------------------------------

class TestSaltVsMatlab14N:
    """Compare salt powder ENDOR to MATLAB for 14N isotropic A=30 MHz."""

    def _load(self):
        path = _require_mat("salt_ref_14N.mat")
        return loadmat(str(path))

    def test_cosine_similarity(self):
        data = self._load()
        x_ref = data["x_salt2"].ravel()
        y_ref = data["y_salt2"].ravel()

        sys = SpinSystem(S=[0.5], g=[[2.0, 2.0, 2.0]], Nucs=["14N"], A=[[30.0, 30.0, 30.0]])
        exp_salt = Experiment(mwFreq=9.5, Range=[330.0, 350.0], nPoints=256)

        x_our, y_our = salt(
            sys,
            exp_salt,
            opt=Options(GridSize=31, Verbosity=0),
            freq_range=(float(x_ref.min()), float(x_ref.max())),
            n_points=len(x_ref),
            lw_mhz=0.5,
        )

        y_our_np = y_our.numpy()
        if y_ref.max() == 0 or y_our_np.max() == 0:
            pytest.skip("One spectrum is all zeros; skipping cosine check")

        cos = _cosine_similarity(y_ref, y_our_np)
        assert cos > 0.92, f"Cosine similarity {cos:.4f} < 0.92"
