"""Tests for torchspin.spinops.sop."""
import math
import os

import pytest
import torch

from torchspin.spinops import sop

# Path to MATLAB reference .mat files (generated by generate_ref_spinops.m)
_DATA_DIR = os.path.join(
    os.path.dirname(__file__), '..', '..', 'tests', 'data'
)


# ---------------------------------------------------------------------------
# Single-spin operators: compare against MATLAB reference .mat files
# ---------------------------------------------------------------------------

def _load_ref(S: float):
    """Load MATLAB reference spin operators for spin S."""
    try:
        from scipy.io import loadmat
    except ImportError:
        pytest.skip("scipy not available")

    fname = os.path.join(_DATA_DIR, f'ref_spinops_S{S}.mat')
    if not os.path.exists(fname):
        pytest.skip(
            f"Reference file not found: {fname}\n"
            "Run tests/data/generate_ref_spinops.m in MATLAB to generate it."
        )
    mat = loadmat(fname)
    return mat['SX'], mat['SY'], mat['SZ']


@pytest.mark.parametrize('S', [0.5, 1.0])
def test_sop_single_spin_vs_matlab(S: float):
    SX_ref, SY_ref, SZ_ref = _load_ref(S)
    dtype = torch.complex128

    SX = sop([S], 'x', dtype=dtype)
    SY = sop([S], 'y', dtype=dtype)
    SZ = sop([S], 'z', dtype=dtype)

    def maxdiff(a, b):
        return (a - torch.from_numpy(b).to(dtype)).abs().max().item()

    assert maxdiff(SX, SX_ref) < 1e-12, f"Sx mismatch for S={S}"
    assert maxdiff(SY, SY_ref) < 1e-12, f"Sy mismatch for S={S}"
    assert maxdiff(SZ, SZ_ref) < 1e-12, f"Sz mismatch for S={S}"


# ---------------------------------------------------------------------------
# Commutation relations  [Sx, Sy] = i Sz  for various spins
# ---------------------------------------------------------------------------

@pytest.mark.parametrize('S', [0.5, 1.0, 1.5, 2.0])
def test_commutation_relations(S: float):
    dtype = torch.complex128
    Sx = sop([S], 'x', dtype=dtype)
    Sy = sop([S], 'y', dtype=dtype)
    Sz = sop([S], 'z', dtype=dtype)

    comm_xy = Sx @ Sy - Sy @ Sx
    assert (comm_xy - 1j * Sz).abs().max().item() < 1e-12, \
        f"[Sx,Sy] != i*Sz  for S={S}"

    comm_yz = Sy @ Sz - Sz @ Sy
    assert (comm_yz - 1j * Sx).abs().max().item() < 1e-12, \
        f"[Sy,Sz] != i*Sx  for S={S}"

    comm_zx = Sz @ Sx - Sx @ Sz
    assert (comm_zx - 1j * Sy).abs().max().item() < 1e-12, \
        f"[Sz,Sx] != i*Sy  for S={S}"


# ---------------------------------------------------------------------------
# S² = S(S+1) * I
# ---------------------------------------------------------------------------

@pytest.mark.parametrize('S', [0.5, 1.0, 1.5])
def test_S_squared(S: float):
    dtype = torch.complex128
    Sx = sop([S], 'x', dtype=dtype)
    Sy = sop([S], 'y', dtype=dtype)
    Sz = sop([S], 'z', dtype=dtype)
    n = int(round(2 * S + 1))

    S2 = Sx @ Sx + Sy @ Sy + Sz @ Sz
    expected = S * (S + 1) * torch.eye(n, dtype=dtype)
    assert (S2 - expected).abs().max().item() < 1e-12, \
        f"S² != S(S+1)*I  for S={S}"


# ---------------------------------------------------------------------------
# Ladder operators
# ---------------------------------------------------------------------------

@pytest.mark.parametrize('S', [0.5, 1.0])
def test_ladder_operators(S: float):
    dtype = torch.complex128
    Sx = sop([S], 'x', dtype=dtype)
    Sy = sop([S], 'y', dtype=dtype)
    Sp = sop([S], '+', dtype=dtype)
    Sm = sop([S], '-', dtype=dtype)

    # S+ = Sx + i*Sy,  S- = Sx - i*Sy
    assert (Sp - (Sx + 1j * Sy)).abs().max().item() < 1e-12, \
        f"S+ != Sx + i*Sy  for S={S}"
    assert (Sm - (Sx - 1j * Sy)).abs().max().item() < 1e-12, \
        f"S- != Sx - i*Sy  for S={S}"


# ---------------------------------------------------------------------------
# Multi-spin: dimension and structure
# ---------------------------------------------------------------------------

def test_multispin_dimension():
    """Operator on a 2-spin system has the correct Hilbert-space dimension."""
    spins = [0.5, 1.0]
    n = int(round(2 * 0.5 + 1)) * int(round(2 * 1.0 + 1))  # 2*3 = 6
    Op = sop(spins, 'xe')
    assert Op.shape == (n, n), f"Expected ({n},{n}), got {Op.shape}"


def test_multispin_xe_is_kron_Sx_I():
    """sop([0.5,0.5], 'xe') == kron(Sx, I)."""
    dtype = torch.complex128
    Sx = sop([0.5], 'x', dtype=dtype)
    I2 = torch.eye(2, dtype=dtype)
    expected = torch.kron(Sx, I2)

    result = sop([0.5, 0.5], 'xe', dtype=dtype)
    assert (result - expected).abs().max().item() < 1e-12


def test_multispin_ez_is_kron_I_Sz():
    """sop([0.5,0.5], 'ez') == kron(I, Sz)."""
    dtype = torch.complex128
    Sz = sop([0.5], 'z', dtype=dtype)
    I2 = torch.eye(2, dtype=dtype)
    expected = torch.kron(I2, Sz)

    result = sop([0.5, 0.5], 'ez', dtype=dtype)
    assert (result - expected).abs().max().item() < 1e-12


def test_multispin_numeric_spec():
    """Numeric spec [[1,1]] matches string spec 'xe' for 2-spin system."""
    dtype = torch.complex128
    r_str = sop([0.5, 0.5], 'xe', dtype=dtype)
    r_num = sop([0.5, 0.5], [[1, 1]], dtype=dtype)  # spin 1, x-component
    assert (r_str - r_num).abs().max().item() < 1e-12


def test_multispin_product_SxSz():
    """sop([0.5,0.5], [[1,1],[2,3]]) == kron(Sx, Sz)."""
    dtype = torch.complex128
    Sx = sop([0.5], 'x', dtype=dtype)
    Sz = sop([0.5], 'z', dtype=dtype)
    expected = torch.kron(Sx, Sz)

    result = sop([0.5, 0.5], [[1, 1], [2, 3]], dtype=dtype)
    assert (result - expected).abs().max().item() < 1e-12


# ---------------------------------------------------------------------------
# Identity operator
# ---------------------------------------------------------------------------

def test_identity_operator():
    """sop([1.0], 'e') == I_3."""
    dtype = torch.complex128
    result = sop([1.0], 'e', dtype=dtype)
    expected = torch.eye(3, dtype=dtype)
    assert (result - expected).abs().max().item() < 1e-12


# ---------------------------------------------------------------------------
# commute
# ---------------------------------------------------------------------------

class TestCommute:
    def test_commutator_zero_for_same(self):
        """[A, A] = 0."""
        import torch
        from torchspin.spinops import sop, commute
        Sx = sop(0.5, 'x')
        C = commute(Sx, Sx)
        assert C.abs().max().item() < 1e-14

    def test_sx_sy_commutator(self):
        """[Sx, Sy] = i*Sz for S=1/2."""
        import torch
        from torchspin.spinops import sop, commute
        Sx = sop(0.5, 'x')
        Sy = sop(0.5, 'y')
        Sz = sop(0.5, 'z')
        C = commute(Sx, Sy)
        expected = 1j * Sz
        assert (C - expected).abs().max().item() < 1e-13

    def test_sy_sz_commutator(self):
        """[Sy, Sz] = i*Sx for S=1/2."""
        import torch
        from torchspin.spinops import sop, commute
        Sy = sop(0.5, 'y')
        Sz = sop(0.5, 'z')
        Sx = sop(0.5, 'x')
        C = commute(Sy, Sz)
        expected = 1j * Sx
        assert (C - expected).abs().max().item() < 1e-13

    def test_sz_sx_commutator(self):
        """[Sz, Sx] = i*Sy for S=1/2."""
        import torch
        from torchspin.spinops import sop, commute
        Sz = sop(0.5, 'z')
        Sx = sop(0.5, 'x')
        Sy = sop(0.5, 'y')
        C = commute(Sz, Sx)
        expected = 1j * Sy
        assert (C - expected).abs().max().item() < 1e-13

    def test_antisymmetry(self):
        """[A, B] = -[B, A]."""
        import torch
        from torchspin.spinops import sop, commute
        Sx = sop(0.5, 'x')
        Sy = sop(0.5, 'y')
        assert (commute(Sx, Sy) + commute(Sy, Sx)).abs().max().item() < 1e-14

    def test_shape_mismatch_raises(self):
        import torch
        from torchspin.spinops import commute
        A = torch.eye(2, dtype=torch.complex128)
        B = torch.eye(3, dtype=torch.complex128)
        with pytest.raises(ValueError, match="same shape"):
            commute(A, B)

    def test_spin_one(self):
        """[Sx, Sy] = i*Sz for S=1."""
        import torch
        from torchspin.spinops import sop, commute
        Sx = sop(1.0, 'x')
        Sy = sop(1.0, 'y')
        Sz = sop(1.0, 'z')
        C = commute(Sx, Sy)
        expected = 1j * Sz
        assert (C - expected).abs().max().item() < 1e-13
