"""MATLAB cross-validation for curry (magnetometry) and blochsteady.

References generated by ``tests/data/generate_curry_bloch_refs.m``
(EasySpin, MATLAB R2024b).
"""

import os

import numpy as np
import pytest

try:
    from scipy.io import loadmat
except ImportError:  # pragma: no cover
    loadmat = None

from torchspin import SpinSystem
from torchspin.blochsteady import blochsteady
from torchspin.constants import BMAGN, BOLTZMANN
from torchspin.curry import curry

DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "tests", "data")

# Avogadro constant (CODATA, exact)
_NA = 6.02214076e23
# Vacuum permeability (H/m)
_MU0 = 1.25663706127e-6


def _load_data(filename):
    if loadmat is None:
        pytest.skip("scipy not installed")
    path = os.path.join(DATA_DIR, filename)
    if not os.path.exists(path):
        pytest.skip(f"Reference file not found: {path}")
    return loadmat(path, simplify_cells=True)["data"]


def test_curry_simplemag():
    """AF-coupled S=1/2 dimer magnetization vs field at 1 K: <0.5% error."""
    ref = _load_data("curry_simplemag.mat")
    sys = SpinSystem(S=[0.5, 0.5],
                     g=[[2.0, 2.0, 2.0], [2.0, 2.0, 2.0]],
                     ee=[-2 * -4 * 30e3])
    B = np.asarray(ref['B'], dtype=float).ravel()
    mu, _ = curry(sys, B.tolist(), [1.0])
    mu = np.asarray(mu).reshape(len(B))
    m_ref = np.asarray(ref['muBM'], dtype=float).ravel()
    scale = max(np.abs(m_ref).max(), 1e-30)
    np.testing.assert_allclose(mu, m_ref, atol=5e-3 * scale,
                               err_msg="curry muBM mismatch vs EasySpin")


def test_curry_simplechi():
    """AF dimer molar susceptibility vs T at 1 T: <0.5% error."""
    ref = _load_data("curry_simplechi.mat")
    sys = SpinSystem(S=[0.5, 0.5],
                     g=[[2.0, 2.0, 2.0], [2.0, 2.0, 2.0]],
                     ee=[-2 * -4 * 30e3])
    T = np.asarray(ref['T'], dtype=float).ravel()
    _, chi = curry(sys, [1000.0], T.tolist())
    chi = np.asarray(chi).reshape(len(T))
    chi_ref = np.asarray(ref['chimol'], dtype=float).ravel()
    scale = np.abs(chi_ref).max()
    np.testing.assert_allclose(chi, chi_ref, atol=5e-3 * scale,
                               err_msg="curry chimol mismatch vs EasySpin")


def test_curry_GdCu_mueff():
    """Gd(III)-Cu(II) chimol and mueff vs T at 100 mT: <1% error.

    EasySpin: curry_mueffGdCu.m (Hatscher et al., Pure Appl. Chem. 77, 497).
    """
    ref = _load_data("curry_GdCu.mat")
    sys = SpinSystem(S=[3.5, 0.5],
                     g=[[2.0023, 2.0023, 2.0023], [2.0023, 2.0023, 2.0023]],
                     ee=[-2 * 5 * 30e3])
    T = np.asarray(ref['T'], dtype=float).ravel()
    _, chi = curry(sys, [100.0], T.tolist(), delta_B=0.01)
    chi = np.asarray(chi).reshape(len(T))
    chi_ref = np.asarray(ref['chimol'], dtype=float).ravel()
    scale = np.abs(chi_ref).max()
    np.testing.assert_allclose(chi, chi_ref, atol=1e-2 * scale,
                               err_msg="curry GdCu chimol mismatch")

    # mueff from chi (SI): mueff = sqrt(3 kB chi T / (mu0 NA muB^2))
    mueff = np.sqrt(3 * BOLTZMANN * chi * T / (_MU0 * _NA * BMAGN ** 2))
    mueff_ref = np.asarray(ref['mueff'], dtype=float).ravel()
    np.testing.assert_allclose(mueff, mueff_ref,
                               atol=1e-2 * np.abs(mueff_ref).max(),
                               err_msg="curry GdCu mueff mismatch")


def test_curry_S1_D():
    """S=1 with D=5 GHz: chimol vs T at 100 mT, <1% error."""
    ref = _load_data("curry_S1_D.mat")
    sys = SpinSystem(S=[1.0], g=[[2.1, 2.1, 2.1]], D=[[5e3, 0.0]])
    T = np.asarray(ref['T'], dtype=float).ravel()
    _, chi = curry(sys, [100.0], T.tolist())
    chi = np.asarray(chi).reshape(len(T))
    chi_ref = np.asarray(ref['chimol'], dtype=float).ravel()
    scale = np.abs(chi_ref).max()
    np.testing.assert_allclose(chi, chi_ref, atol=1e-2 * scale,
                               err_msg="curry S=1 D chimol mismatch")


def test_blochsteady_simple():
    """Steady-state Bloch magnetization under field modulation: cosine >= 0.999.

    EasySpin: blochsteady_simple.m (g=gfree, T1=20, T2=1 µs, 50 kHz mod).
    """
    ref = _load_data("blochsteady_simple.mat")
    g, T1, T2, dB0, B1, modamp, modfreq = np.asarray(
        ref['params'], dtype=float).ravel()
    t, Mx, My, Mz = blochsteady(g, T1, T2, dB0, B1, modamp, modfreq)

    for name, sig, key in (('Mx', Mx, 'Mx'), ('My', My, 'My'),
                           ('Mz', Mz, 'Mz')):
        a = np.asarray(sig, dtype=float).ravel()
        b = np.asarray(ref[key], dtype=float).ravel()
        n = min(len(a), len(b))
        if len(a) != len(b):
            # Different time resolution: interpolate onto reference axis
            t_py = np.asarray(t, dtype=float).ravel()
            t_ref = np.asarray(ref['t'], dtype=float).ravel()
            a = np.interp(t_ref, t_py, np.asarray(sig, dtype=float).ravel())
            b = np.asarray(ref[key], dtype=float).ravel()
            n = len(b)
        cos = abs(np.dot(a[:n], b[:n])) / (
            np.linalg.norm(a[:n]) * np.linalg.norm(b[:n]) + 1e-30)
        assert cos > 0.999, f"blochsteady {name} cosine {cos:.5f} < 0.999"
